### ISSUE TITLE
Install fails because of GitHub api rate limiting

### ISSUE THREAD

**Issue by egeland** [databus23/helm-diff#10]
As per doco, I run `helm plugin install https://github.com/databus23/helm-diff`, and I get:
```
$ helm plugin install https://github.com/databus23/helm-diff
Downloading
curl: (3) <url> malformed
Failed to install helm-diff
\tFor support, go to https://github.com/databus23/helm-diff.
Error: plugin install hook for "diff" exited with error
```

My helm:
```
$ helm version
Client: &version.Version{SemVer:"v2.5.0", GitCommit:"012cb0ac1a1b2f888144ef5a67b8dab6c2d45be6", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.5.0", GitCommit:"012cb0ac1a1b2f888144ef5a67b8dab6c2d45be6", GitTreeState:"clean"}
```

**Comment by egeland** [comment]
From some investigation, we are hitting the github api rate limit (NAT'ed egress IP from an office full of developers).

**Comment by databus23** [comment]
Ah that darn github api rate limit...
I could try to guess the download url from the plugin version and platform instead of using the api for getting the download url.
To be honest I just copied the install script from [helm-template](https://github.com/technosophos/helm-template) and haven't given it much thought.
I'm going to leave this open for now and wait a bit to this if this is a frequent problem that needs fixing.

**Comment by egeland** [comment]
Maybe just returning the error from the `curl` attempt would help people understand what the problem is.
Other than that, maybe add the option to use an API token (from an env var) to get around the unauthenticated api limits?

**Comment by mellowplace** [comment]
I think I've just hit this problem in a Docker build...

```
Downloading 
curl: (3) <url> malformed
Failed to install helm-diff
\tFor support, go to https://github.com/databus23/helm-diff.
Error: plugin install hook for "diff" exited with error
```

**Comment by helgi** [comment]
#69 fixed this for the scenario when you ask for a specific version; The GH API is still used to determine the latest version.

**Comment by rajiteh** [comment]
Still seeing this issue.
```
helm --debug plugin install https://github.com/databus23/helm-diff --version master
[debug] cloning https://github.com/databus23/helm-diff to /root/.helm/cache/plugins/https-github.com-databus23-helm-diff
[debug] setting version to "master"
[debug] symlinking /root/.helm/cache/plugins/https-github.com-databus23-helm-diff to /root/.helm/plugins/helm-diff
[debug] loading plugin from /root/.helm/plugins/helm-diff
[debug] running install hook: &{/bin/sh [sh -c $HELM_PLUGIN_DIR/install-binary.sh] []  <nil> <nil> <nil> [] %!s(*syscall.SysProcAttr=<nil>) %!s(*os.Process=<nil>) <nil> <nil> <nil> %!s(bool=false) [] [] [] [] %!s(chan error=<nil>) %!s(chan struct {}=<nil>)}
Downloading 
Failed to install helm-diff
\tFor support, go to https://github.com/databus23/helm-diff.
curl: (3) <url> malformed
Error: plugin install hook for "diff" exited with error
```
