### ISSUE TITLE
values from stdin

### ISSUE THREAD

**Issue by okgolove** [databus23/helm-diff#101]
I store my values in some place in base64.
It would be great if I was able to do something like this:

```
sed "s|foo|bar|g" values-template.yaml | helm install -f - stable/foo
```

`helm` can do it - https://github.com/helm/helm/issues/2709

**Comment by databus23** [comment]
Thanks for the idea. If helm supports this then`helm diff` should too IMO. I don't have time to look into this at the moment though, a PR for this would be more then welcome.

**Comment by cdancy** [comment]
Would love to have this feature!

**Comment by okgolove** [comment]
I've added some code to implement this feature.

**Comment by okgolove** [comment]
@databus23 any updates? I really need this feature and wouldn't want build it locally with these changes.

**Comment by mumoshu** [comment]
Sorry for the delayed response. I'm looking into your PR now 🙏
