### ISSUE TITLE
Enhancement: --suppress-secrets but only hide values

### ISSUE THREAD

**Issue by mkj28** [databus23/helm-diff#103]
--suppress-secrets is great, but it hides that secrets will be deleted/created, so you don't know you may be deleting something important.

Currently you get:
`+ Changes suppressed on sensitive content of type Secret`, even better would be showing which secret is being changed and how (deleted/created/modified but hide values).

**Comment by databus23** [comment]
Thanks for the idea. I like it. I don't have the time to work an this though at the moment. PRs are welcome
