### ISSUE TITLE
Upgrade to helm 2.13

### ISSUE THREAD

**Issue by jkroepke** [databus23/helm-diff#112]
Hi,

can you provide a new binary which is build agist helm 2.12?

**Comment by nce** [comment]
We'r having the same request. Especially after the Helm 2.12.2 Release.

**Comment by databus23** [comment]
See my comment on the matter here: 
https://github.com/databus23/helm-diff/pull/113#issuecomment-454308756

**Comment by jkroepke** [comment]
Didn‘t know it. thanks

**Comment by databus23** [comment]
@okgolove I think this does not apply for this diff plugin. the template rendering is done by tiller. this plugin only uses the helm client to talk to tiller and upload the `chart/manifest`.

**Comment by jkroepke** [comment]
@databus23 
On 2.13.0 (https://github.com/helm/helm/releases/tag/v2.13.0) , helm does some GRPC protocol changes. Right?

So helm diff needs an upgrade right now?

**Comment by willejs** [comment]
This would fix the below issue too.
https://github.com/databus23/helm-diff/issues/107
I am going to rebuild to test this out, but I am 99.9% sure.

**Comment by sonnysideup** [comment]
any movement on this?
