### ISSUE TITLE
Diff shown for tests

### ISSUE THREAD

**Issue by cablespaghetti** [databus23/helm-diff#114]
Helm's test feature allows you to put definitions of test resources in `templates/test/`. However I don't want helm diff to print out these changes because they don't actually do anything in a normal `helm upgrade` command.

To reproduce this, run something like
```
helm diff --allow-unreleased upgrade keycloak-test-release stable/keycloak
```

**Comment by regner** [comment]
This causes issue in Helmsman which uses helm-diff to figure out which charts need to be upgraded and marks any chart with tests as needing an upgrade.

**Comment by regner** [comment]
If I understand right this PR should solve this: https://github.com/databus23/helm-diff/pull/118

**Comment by cablespaghetti** [comment]
@regner Yes it annoys me using https://github.com/roboll/helmfile

I'm not sure from that PR how the feature is supposed to be used. It might not solve my problem because I probably don't want to ignore all hooks, just ones relating to tests.

**Comment by regner** [comment]
Fairly new to Helm. What other hooks might you want to be kept enabled?

**Comment by cablespaghetti** [comment]
I'm not sure especially when using public charts which I didn't develop. That's the problem. :(

**Comment by regner** [comment]
Yeah those hooks for post install I can see being important.

**Comment by mumoshu** [comment]
@regner @cablespaghetti Hey! Thanks for the continued discussion and the fix this. I appreciate it.

Do you think we can exclude tests from the diff by default? That is, make the flag named `--include-tests` and default to `--include-tests=false`, thinking tests are only run on `helm test` and usually you don't need it included in a diff.

**Comment by mumoshu** [comment]
Or make `--no-tests=true` the default - in a case that we prefer consistency with the existing flag `--no-hooks=false`

**Comment by regner** [comment]
I think it's safe to exclude tests by default yeah. I don't see a case where you would want tests to be included in the diff. I would just make sure it is clearly stated in the release notes incase someone is relying on it for something.

Would you like me to make the change so that it is based on `--include-tests` and defaults to false?

**Comment by mumoshu** [comment]
> make sure it is clearly stated in the release notes incase someone is relying on it for something.

Sounds good! Will do so.

> make the change so that it is based on `--include-tests` and defaults to false?

Yes! I'd appreciate it if you could do so.

**Comment by regner** [comment]
Sorry for the delay. I have now pushed the requested change to #119.

**Comment by cablespaghetti** [comment]
Any chance of a release with this in? I'm keen to start using it. :)
