### ISSUE TITLE
helm diff ignores --set-file

### ISSUE THREAD

**Issue by excavador** [databus23/helm-diff#117]
argument `--set-file` ignored by helm diff, it show incorrect output

**Comment by excavador** [comment]
---set-file works correctly, my bad

**Comment by andreub** [comment]
@excavador does it work? can you please provide with some details on how to do it please?

**Comment by excavador** [comment]
`helm diff --set-file=path/to/file`

**Comment by excavador** [comment]
the same with https://github.com/helm/helm/blob/master/docs/helm/helm_install.md

**Comment by andreub** [comment]
thanks! not working for me, maybe is my diff version, anyway I don't see it documented anywhere..

**Comment by excavador** [comment]
Did you try: ```helm diff upgrade --set-file=yaml.key=path/to/file```?
`helm diff` makes sense only for `helm diff upgrade`
