### ISSUE TITLE
`helm diff upgrade` doesn't respect the helm hook annotation

### ISSUE THREAD

**Issue by SongGithub** [databus23/helm-diff#122]
for example, 
```
# helm/foo-app/template/hooks/secrets.yaml
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "fullname" . }}
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": "before-hook-creation"
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  sentry-secret: {{ default (randAlphaNum 40) .Values.sentrySecret | b64enc | quote }}
  smtp-password: {{ default "" .Values.email.password | b64enc | quote }}
  user-password: {{ default (randAlphaNum 16) .Values.user.password | b64enc | quote }}
```
when I run `helm diff upgrade`, I expect to see the password not changed. however, it seems that it ignores the annotation and showing passwords will be changed.

**Comment by regner** [comment]
What does the hook have to do with that?

It also appears you're using `default` wrong. I believe it is supposed to be formatted as:

```
  sentry-secret: {{ .Values.sentrySecret | default (randAlphaNum 40) | b64enc | quote }}
```

**Comment by regner** [comment]
For clarity on the hooks: All the templates are generated at once, the hooks control the order in which they are applied to Kubernetes.

**Comment by viroos** [comment]
We have the same issue. Why it was closed? :(

**Comment by regner** [comment]
It was closed by the original creator of the issue because there was no issue with helm-diff. I would recommend opening a new issue with details and examples of your specific issue.
