### ISSUE TITLE
Run CircleCI tests on pull requests

### ISSUE THREAD

**Issue by regner** [databus23/helm-diff#124]
It appears CircleCI is not configured to run against PRs. This makes sense when there are potential secrets that could be exposed however based on what CircleCI runs it doesn't appear to consume any secrets.

Running CircleCI against PR commits would help expose issues before they get into master, such as what happened with #119.

**Comment by databus23** [comment]
Sorry for long delay. But I'm happy to report that I think this is fixed as of right now.
