### ISSUE TITLE
plugin version 2.11.0+4  does not work in Alpine Linux 

### ISSUE THREAD

**Issue by Chili-Man** [databus23/helm-diff#141]
The latest published binaries for 2.11.0+4 are dynamically linked binaries against `/lib64/ld-linux-x86-64.so.2` , which are not supported in Alpine Linux. The previous version 2.11.0+3 was statically linked so we didn't have that problem. When we try to run it, we get this issue:

Can we go back to statically compiling the helm diff binaries?

version 2.11.0+3:
```shell
bash-4.4# file ./diff 
./diff: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), statically linked, not stripped
bash-4.4# helm plugin list
NAME	VERSION 	DESCRIPTION                           
diff	2.11.0+3	Preview helm upgrade changes as a diff
```

version 2.11.0+4
```shell
bash-4.4# file ./diff 
./diff: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, not stripped

bash-4.4# helm plugin list
NAME	VERSION 	DESCRIPTION                           
diff	2.11.0+4	Preview helm upgrade changes as a diff

bash-4.4# ./diff 
bash: ./diff: No such file or directory
```

**Comment by victornoel** [comment]
I second this, I'm having the same problem

**Comment by iAnomaly** [comment]
Same problem here. Additionally `helm plugin install https://github.com/databus23/helm-diff --version 2.11.0+3` doesn't seem to be parsed/respected and helm ends up downloading/installing `v2.11.0+1`

**Comment by iAnomaly** [comment]
Same here. If you need a workaround for now be sure to explicitly specify the previous version at install:
`helm plugin install https://github.com/databus23/helm-diff --version v2.11.0+3`

**Comment by nullbyte61** [comment]
> Same here. If you need a workaround for now be sure to explicitly specify the previous version at install:
> `helm plugin install https://github.com/databus23/helm-diff --version v2.11.0+3`

Thank you, this would do for the time being

**Comment by databus23** [comment]
I have just released v2.11.0+5 which should be back to statically linked binaries. Can someone please confirm that this fixes the reported issue?

**Comment by nullbyte61** [comment]
Just tried and it works now with master release (v2.11.0+5)

**Comment by databus23** [comment]
Thanks. Closing this now.
