### ISSUE TITLE
Thanks a lot

### ISSUE THREAD

**Issue by karuppiah7890** [databus23/helm-diff#143]
Thanks a lot for creating this awesome tool! Our team uses this extensively to check diffs before installing or upgrading any release in helm!

We will soon be contributing to this repository, in any possible way we can 😄

**Comment by tariq1890** [comment]
I echo this sentiment :). Thanks @databus23

**Comment by vikas027** [comment]
+1

Works perfectly with Kubernetes v1.15.2 and Helm v2.14.3 (latest as on date)

**Comment by databus23** [comment]
Thanks for the nice feedback. I'm closing this as its not about an open issue that requires attention.
