### ISSUE TITLE
Option to ignore line endings

### ISSUE THREAD

**Issue by michaelgeorgeattard** [databus23/helm-diff#144]
When a particular upgrade/release has been made with CRLF line ending template files, and a diff is made with a LF line ending version of the same template files, `helm diff` shows the line ending change as a difference (as expected).

Is it currently possible to ignore line ending changes when generating the diff?

**Comment by ranjanashish** [comment]
It would be great if helm-diff has certain flags which users can use to ignore differences in line endings and, also, comments (since comments are not going to affect the workload).

**Comment by mebays** [comment]
I just started using helm diff and this would be a great feature to incorporate.

**Comment by shimodatkh** [comment]
I have just faced this problem. It would be great if an option to ignore line endings was implemented!

**Comment by mumoshu** [comment]
Could anyone submit a pull request for this? This sounds like a good addition to helm-diff.

**Comment by mumoshu** [comment]
This has been added via #237 thanks to @bakito 😄
