### ISSUE TITLE
Output should show the diff only

### ISSUE THREAD

**Issue by RobertoUa** [databus23/helm-diff#152]
Currently, when I run diff it outputs the whole manifest which makes it hard to locate the actual changes in a big project. It would be much nicer to show only changes to manifest like in `git diff` for example.

**Comment by databus23** [comment]
If I'm not mistaken the `--context` flag should be solving your problem. Closing this issue for now. Feel free to reopen I've misunderstood the problem.

**Comment by RobertoUa** [comment]
awesome, thank you!
