### ISSUE TITLE
helm diff (v3) does not work when crd resources are generated

### ISSUE THREAD

**Issue by databus23** [databus23/helm-diff#158]
It turns out that `helm template` (which we call out when doing `helm diff upgrade` with helm version 3 ), refuses to render resources in client-only mode that use anything but the default api versions:
This PR tries to address this in helm https://github.com/helm/helm/pull/6729 disabling the version check.

Using `--validate` as suggested here https://github.com/helm/helm/issues/6680 is not an option because it will cause `helm template` to fail if the rendered resource already exists in the cluster: https://github.com/helm/helm/issues/6663

So at the moment the only option to diff a chart that renders crd resources is to explicitly pass the  `--api-versions` flag to `helm template`.

My hope is that https://github.com/helm/helm/pull/6729 is merged fixing this. Its quite tedious that the user of `helm diff` needs to know (and specify) which apiversions are used in the chart (or any dependency) otherwise.

I created a workaround for now that hopefully can be removed eventually https://github.com/databus23/helm-diff/commit/cd5743f15132aaecf2d5ecb449744d2151b05666. So by manually specifying `HELM_TEMPLATE_API_VERSIONS` the api version check of `helm template` can be satisfied.

**Comment by mumoshu** [comment]
@databus23 Thanks. I've commented on the upstream issue: https://github.com/helm/helm/pull/6729#issuecomment-546798288

Broadly speaking, I think it's a kind of an upstream regression and the PR has some value to be merged before 3.0.0 goes GA 🤔

**Comment by thomastaylor312** [comment]
@mumoshu Thanks for bringing this up in the Helm issue. @databus23 I'm talking to the other maintainers because you aren't the only ones who have ran into this. We'll update that PR if people are all in agreement with bringing it in to 3.0.0

**Comment by mumoshu** [comment]
@thomastaylor312 Thanks as always for your support 👍 

@databus23 We still have on-going discussions in https://github.com/helm/helm/pull/6729 but anyway - https://github.com/helm/helm/pull/6729 won't be merged as-is.

A possible alternative that may work, from the helm-diff pov, is to change  `--helm template --validate=false` to actually disable api versions check and helm-diff uses that. Does it sound good to you?

**Comment by mumoshu** [comment]
> to change  `--helm template --validate=false` to actually disable api versions check and helm-diff uses that

Sorry I think that's what https://github.com/helm/helm/pull/6729 is (already) intended for :)

**Comment by thomastaylor312** [comment]
@databus23 We should have fixed this with the latest master. We had some code that was left over in a sorting method that was validating API versions. Now `helm template` will not try to validate your APIs unless you have passed the `--validate` flag

**Comment by databus23** [comment]
Indeed the problem seems to be fixed with 3.0.0-rc.1. Hurray!
