### ISSUE TITLE
Helm 3: Error: Couldn't load repositories file (repository\repositories.yaml). You might need to run `helm init`

### ISSUE THREAD

**Issue by Skaronator** [databus23/helm-diff#161]
I'm currently trying to setup helm 3 with helmfile and helm-diff but I run in some weird issues. When running helm file with debug mode I notice that the following command cause issues for helmfile:
`helm diff upgrade --reset-values --allow-unreleased test charts\test --namespace default --detailed-exitcode`

When running this command on my own (without helmfile) I get a more detailed error:

```
$ helm diff upgrade --reset-values --allow-unreleased test charts\test --namespace default --detailed-exitcode
Error: Couldn't load repositories file (repository\repositories.yaml).
You might need to run `helm init` (or `helm init --client-only` if tiller is already installed)
Couldn't load repositories file (repository\repositories.yaml).
You might need to run `helm init` (or `helm init --client-only` if tiller is already installed)
Error: plugin "diff" exited with error
```

This error suggest that I should run `helm init` but `helm init` doesn't exist anymore on Helm 3. Any ideas how to fix this issue?

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T19:18:23Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T19:09:08Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}

$ helm version
version.BuildInfo{Version:"v3.0.0-rc.1", GitCommit:"ee77ae3d40fd599445ebd99b8fc04e2c86ca366c", GitTreeState:"clean", GoVersion:"go1.13.3"}

$ helm plugin list
NAME    VERSION         DESCRIPTION
diff    3.0.0-rc.6      Preview helm upgrade changes as a diff

$ helm diff version
2.11.0+5 (????)

$ helmfile --version
helmfile version v0.90.1
```

**Comment by databus23** [comment]
> helm diff version
> 2.11.0+5 (????)

Ok this is some serious foo. It should be reporting 3.0.0-rc.6 (it does for me). So it looks like your plugin directory got messed up and you have a v2.11.0+5 diff binary laying around in a checkout that should contain the 3.0.0-rc.6 binary

**Comment by Skaronator** [comment]
Ah! Thanks for the hint. I had installed the master branch instead of the 3.0.0-rc.6 version.

```diff
- helm plugin install https://github.com/databus23/helm-diff --version master
+ helm plugin install https://github.com/databus23/helm-diff --version v3.0.0-rc.6
```

```
$ helm diff version
3.0.0-rc.6
```

**Comment by deiga** [comment]
I had the same issue today that `--version master` would install `2.11.0+5` instead of `3.0.0-rc.7`

**Comment by colearendt** [comment]
Me as well. Moreover, `helm plugins list` showed `3.0.0-rc.7`. It was only `helm diff version` that showed `2.11.0+5`.
