### ISSUE TITLE
Support diff by chart reference and repo url (--repo option)

### ISSUE THREAD

**Issue by scottrigby** [databus23/helm-diff#164]
`helm install` / `helm upgrade --install` have the `--repo` option, so that a chart can be found in a helm repository without adding the repo to the local repositories list. Option 5 from `helm install -h`:

```
There are five different ways you can express the chart you want to install:
1. By chart reference: helm install mymaria example/mariadb
2. By path to a packaged chart: helm install mynginx ./nginx-1.2.3.tgz
3. By path to an unpacked chart directory: helm install mynginx ./nginx
4. By absolute URL: helm install mynginx https://example.com/charts/nginx-1.2.3.tgz
5. By chart reference and repo url: helm install --repo https://example.com/charts/ mynginx nginx
```

The `--repo` option has been in `helm` for years, but has this idea come up for the diff plugin to support this as well? I looked through issues here and didn't find it.

**Comment by emre141** [comment]
Hi,
I am interested in same feature.Why this issue closed by bot ? Is there any alternative helm diff compare chart with yaml using registry like followup

helm diff stable/nginx -f values.prod.yaml 

?
