### ISSUE TITLE
`helm diff version`  show the wrong version number

### ISSUE THREAD

**Issue by shreychen** [databus23/helm-diff#166]
Installed the lates helm diff plugin

`helm plugin list` shows the right version number
> $ helm plugin list
NAME    VERSION         DESCRIPTION                           
diff    3.0.0-rc.7      Preview helm upgrade changes as a diff

while `helm diff version` shows a wrong one
> $ helm diff version 
2.11.0+5

**Comment by databus23** [comment]
Which version of helm are you using? 2 or 3?
In general this suggest there is a mixup in your local plugin folder. The versions should match

**Comment by shreychen** [comment]
I am using helm 3

> $ helm version 
version.BuildInfo{Version:"v3.0.0", GitCommit:"e29ce2a54e96cd02ccfce88bee4f58bb6e2a28b6", GitTreeState:"clean", GoVersion:"go1.13.4"}

run `helm plugin list` with debug
> $ helm plugin  list --debug              
plugin_list.go:32: [debug] pluginDirs: /home/sychen/.local/share/helm/plugins
NAME    VERSION         DESCRIPTION                           
diff    3.0.0-rc.7      Preview helm upgrade changes as a diff

then change dir to /home/sychen/.local/share/helm/plugins/helm-diff, run `git status`
> $ git status
# HEAD detached at **v3.0.0-rc.7**
nothing to commit, working directory clean

then run `./bin/diff version`
> $ ./bin/diff version
**2.11.0+5**

**Comment by shreychen** [comment]
I am using helm 3

> $ helm version 
version.BuildInfo{Version:"v3.0.0", GitCommit:"e29ce2a54e96cd02ccfce88bee4f58bb6e2a28b6", GitTreeState:"clean", GoVersion:"go1.13.4"}

run `helm plugin list` with debug
> $ helm plugin  list --debug              
plugin_list.go:32: [debug] pluginDirs: /home/sychen/.local/share/helm/plugins
NAME    VERSION         DESCRIPTION                           
diff    3.0.0-rc.7      Preview helm upgrade changes as a diff

then change dir to /home/sychen/.local/share/helm/plugins/helm-diff, run `git status`
> $ git status
# HEAD detached at v3.0.0-rc.7
nothing to commit, working directory clean

then run `./bin/diff version`
> $ ./bin/diff version
2.11.0+5

**Comment by shreychen** [comment]
I just try to `uninstall` and `install` the plugin again

uninstall
> $ helm plugin uninstall diff
Uninstalled plugin: diff
install without specifying the version 
> $ helm plugin install https://github.com/databus23/helm-diff 
Downloading https://github.com/databus23/helm-diff/releases/download/v2.11.0%2B5/helm-diff-linux.tgz
bypass the version flag 
> $ helm plugin install https://github.com/databus23/helm-diff --version v3.0.0-rc.7
Downloading https://github.com/databus23/helm-diff/releases/download/v2.11.0%2B5/helm-diff-linux.tgz
both `install` downloaded from the wrong url (v2.11.0), should it a bug related to helm itself ?

**Comment by plnordquist** [comment]
I had an issue similar to this in my environment and I had to update my version of git to fix it.  The line here in the install script https://github.com/databus23/helm-diff/blob/master/install-binary.sh#L69 calls to git with the `-C` flag which does not exist on older versions of git like those installed in RHEL or CentOS.  I don't know what the true fix should be but at least using a version of git that supports that flag seemed to work.

**Comment by shreychen** [comment]
By checking the script `install-binary.sh`, I found the git api to get the latest release indeed return the download url of version 

> $ curl -sSk https://api.github.com/repos/$PROJECT_GH/releases/latest |grep -i linux |grep browser_download_url 
      "browser_download_url": "https://github.com/databus23/helm-diff/releases/download/v2.11.0%2B5/helm-diff-linux.tgz"

And in the releases page, the `latest` tag is now linked to tag `v2.11.0+5`.

you can refer to https://help.github.com/en/github/administering-a-repository/linking-to-releases to update it.
