### ISSUE TITLE
Diff is not working with helm3

### ISSUE THREAD

**Issue by AlexShemeshWix** [databus23/helm-diff#170]
i have test chart https://github.com/wix-playground/helm3diff
my helm version. executable name is helm3
```version.BuildInfo{Version:"v3.0.0", GitCommit:"e29ce2a54e96cd02ccfce88bee4f58bb6e2a28b6", GitTreeState:"clean", GoVersion:"go1.13.4"}```

my helm diff version is ```3.0.0-rc.7```

Ive installed my chart using helm3

```helm3 install simple-cm simple-cm```

its installed ok

```helm3 list```
```simple-cm	sandbox  	1       	2019-12-09 12:05:33.691231 +0200 IST	deployed	simple-cm-0.1.1	1.0```

when i run
```helm3 diff simple-cm simple-cm```
i got
```helm3 diff upgrade simple-cm simple-cm
Error: context deadline exceeded
context deadline exceeded
Error: plugin "diff" exited with error
```

why is that?

**Comment by databus23** [comment]
Sounds like a duplicate of  https://github.com/databus23/helm-diff/issues/167

Try if this makes the problem go away: https://github.com/databus23/helm-diff/issues/167#issuecomment-558535405

**Comment by AlexShemeshWix** [comment]
It may be definitely like #167.
But even if i rollback version fo diff to 3.0.0-rc.6, it wont give any difference to template even i change template dramatically. 
So what do i do? Can somebody from you busy people reproduce my bug and see if we can work around it somehow.

**Comment by aminHatim** [comment]
I have the same issue as @AlexShemeshWix. I don't see the diff.

**Comment by AlexShemeshWix** [comment]
So whats up with that? ended up restricting my versioins
helm3 v3.0.0
helmfile v0.94.1
diff plugin 3.0.0-rc.7
and it works. but i would like to be able to upgrade to latest versions everywhere.

**Comment by deiga** [comment]
@AlexShemeshWix @Am1n3e  Have you tried running latest stable version? 3.1.1 looks to have fixed these `diff` issues.
