### ISSUE TITLE
Issue finding repositories.yaml with master branch

### ISSUE THREAD

**Issue by colearendt** [databus23/helm-diff#171]
A duplicate of https://github.com/databus23/helm-diff/issues/161

That shows:
```
  Error: Couldn't load repositories file (repository/repositories.yaml).
  You might need to run `helm init` (or `helm init --client-only` if tiller is already installed)
  Error: plugin "diff" exited with error
```

Moreover, `helm plugin list` showed version `3.0.0-rc.7`. It was only `helm diff version` that shows the wrong version is installed: `2.11.0+5`.

Solution: `helm plugin uninstall diff` and then reinstall:

```
helm plugin install https://github.com/databus23/helm-diff --version v3.0.0-rc.7
```

**Comment by HaveFun83** [comment]
Thanks for the solution
