### ISSUE TITLE
Help is missing namespace flag

### ISSUE THREAD

**Issue by EssentialMix** [databus23/helm-diff#178]
I assume with helm3 we need to specify "--namespace", but that flag is missing from diff "help"

Also it would be nice if by default it will run helm with "--all-namespaces", so we can keep same behaviour as helm2 have

**Comment by aodj** [comment]
I had the same problem, and so searched the code. It looks like you can set the env var `HELM_NAMESPACE` and specify the namespace that way, but it would be really nice to have the same options as, say, `helm list`:

```bash
  -A, --all-namespaces   list releases across all namespaces
```

**Comment by nicolasbelanger** [comment]
@aodj thanks, I confirm it works with `HELM_NAMESPACE`.  Testing with `helm diff upgrade`

**Comment by sakalys** [comment]
IMO helm diff should mimic the arguments of `helm upgrade`, which includes `--namespace`.
