### ISSUE TITLE
Fails to render stable/prometheus-operator manifests for new install.

### ISSUE THREAD

**Issue by mojochao** [databus23/helm-diff#189]
Versions used:

* helm v3.1.1
* databus23/helm-diff plugin v3.1.1

Problem observed:

I can successfully install the stable/prometheus-operator chart with `helm` directly.

```
$ helm install prometheus-operator stable/prometheus-operator -n monitoring
manifest_sorter.go:192: info: skipping unknown hook: "crd-install"
manifest_sorter.go:192: info: skipping unknown hook: "crd-install"
manifest_sorter.go:192: info: skipping unknown hook: "crd-install"
manifest_sorter.go:192: info: skipping unknown hook: "crd-install"
manifest_sorter.go:192: info: skipping unknown hook: "crd-install"
NAME: prometheus-operator
LAST DEPLOYED: Wed Feb 26 13:13:58 2020
NAMESPACE: monitoring
STATUS: deployed
REVISION: 1
NOTES:
The Prometheus Operator has been installed. Check its status by running:
  kubectl --namespace monitoring get pods -l "release=prometheus-operator"

Visit https://github.com/coreos/prometheus-operator for instructions on how
to create & configure Alertmanager and Prometheus instances using the Operator.
```

If I uninstall the prometheus-operator chart release and just try to `helm diff` it, it fails with:

```
$ helm diff --allow-unreleased upgrade -n monitoring prometheus-operator stable/prometheus-operator
********************

	Release was not present in Helm.  Diff will show entire contents as new.

********************
Error: Failed to render chart: exit status 1: manifest_sorter.go:192: info: skipping unknown hook: "crd-install"
manifest_sorter.go:192: info: skipping unknown hook: "crd-install"
manifest_sorter.go:192: info: skipping unknown hook: "crd-install"
manifest_sorter.go:192: info: skipping unknown hook: "crd-install"
manifest_sorter.go:192: info: skipping unknown hook: "crd-install"
Error: unable to build kubernetes objects from release manifest: [unable to recognize "": no matches for kind "Alertmanager" in version "monitoring.coreos.com/v1", unable to recognize "": no matches for kind "Prometheus" in version "monitoring.coreos.com/v1", unable to recognize "": no matches for kind "PrometheusRule" in version "monitoring.coreos.com/v1", unable to recognize "": no matches for kind "ServiceMonitor" in version "monitoring.coreos.com/v1"]

Error: plugin "diff" exited with error
```

I'm using `helmfile` to drive my installs, and due to this error I am unable to install prometheus-operator with it.  Any ideas on fixes or workarounds for this problem?

Many thanks in advance!

**Comment by mojochao** [comment]
I believe this is the same issue as https://github.com/databus23/helm-diff/issues/183.  Please correct me if I'm wrong.

**Comment by Xartos** [comment]
I have the same issue but for another chart. 
What I found was that when you run `helm diff` on an unreleased chart it will run `helm template ... --validate` which validates the objects with the API server. So in the end this issue is dependent on this issue https://github.com/helm/helm/issues/7449 

One solution would be to add a flag that disables the `--validate` flag here
https://github.com/databus23/helm-diff/blob/4292dcb3cfe21e413ef93e2608c9a8c1f61ebd1a/cmd/helm3.go#L126
something like `--disable-validation`

**Comment by semoac** [comment]
Hi!

I temporally solve this issue installing helm-diff version 3.0.0-rc.7.
We really need a way to control this behavior when using charts with CRD or tools like `helmfile`

**Comment by mumoshu** [comment]
I think this can be resolved by using `--disable-openapi-validation`. We need to publish a new helm-diff release contains that: #220

**Comment by diversario** [comment]
This is still a problem when helm-diff (`3.1.3`) is used by Helmfile's (`0.130.1`) `apply` command.

```
helmfile apply --suppress-diff --suppress-secrets --skip-deps --args="--disable-openapi-validation"
```

fails with
```
Error: Failed to render chart: exit status 1: Error: unable to build kubernetes objects from release manifest: unable to recognize "": no matches for kind "ServiceMonitor" in version "monitoring.coreos.com/v1"
Error: plugin "diff" exited with error
```

**Comment by mumoshu** [comment]
@diversario Could you try setting `disableValidation: true` on the prometheus-operator release in your helmfile.yaml?

The general rule is that if it works with `helm diff upgrade foo prometheus/operator --disable-validation` it works with helmfile, too.

**Comment by sjentzsch** [comment]
I can confirm it works in Helmfile with:
```
helmDefaults:
  disableValidation: true
```

**Comment by diversario** [comment]
Missed this, sorry! Yes, it does work with the `disableValidation: true`, although it's unfortunate that it has to be disabled permanently even though it's required only for the initial install.

**Comment by zak905** [comment]
As a side note: disabling validation on all the releases may lead to other problems. For example, I got: 
```
Error: chart requires kubeVersion: >=1.19.0-0 which is incompatible with Kubernetes v1.16.0
```
on the ingress-nginx. Although I have version a version >= 1.21.0, the error is still thrown. This is because without validation, helm cannot pull the Kubernetes version, so it defaults to v1.16.0. Maybe worth disabling validation on the concerned charts only.

**Comment by mumoshu** [comment]
@zak905 Thanks for sharing! In case the chart requires a valid `.Capabilityes.KubeVersion`, `--kube-version` would be handy https://github.com/databus23/helm-diff/pull/386. Similarly, `.Capabilityes.APIVersions` can be populated via `--api-versions`.
