### ISSUE TITLE
diff not to show the unchanged lines 

### ISSUE THREAD

**Issue by ronyjoy** [databus23/helm-diff#191]
Currently the diff output contains the changed lines, new lines and unchanged lines, Could we utilize the --suppress to suppress the unchanged lines. If you guys agree I can modify the code and submit a pull request the changes will be in the diff.go and remove the diffLib.common if that is passed in --suppress flag
for example : "... --suppress unchangedlines" will remove the unchanged lines from the output

hope it make sense

**Comment by databus23** [comment]
Thats already possible using the `--context,-C` flag, no?

**Comment by ronyjoy** [comment]
interesting , i haven't seen --context, -C in the documentation.

**Comment by ronyjoy** [comment]
Thanks a lot that worked  "helm diff upgrade -C 2" will show 2 line around the changes 
thanks for the quick response
