### ISSUE TITLE
Found duplicate key "resource, , List (v1)" in manifest

### ISSUE THREAD

**Issue by robinelfrink** [databus23/helm-diff#201]
Note this is _not_ a duplicate of #48 or #129 .

A helm chart can generate an object of `kind: List`, which seems to be just another way of writing several objects into one yaml-file.

An example of such a chart is [prometheus-operator](https://github.com/helm/charts/tree/master/stable/prometheus-operator), using `kind: List` in generated ServiceMonitors, PodMonitors etc.

The resulting manifests thus may contain multiple `kind: List` objects, with no name.

**Comment by jesussancheztellomm** [comment]
I am experiencing the same issue with the prometheus-operator chart.

2020/06/24 16:58:11 Error: Found duplicate key "xxx, , List (v1)" in manifest

**Comment by iivanov1** [comment]
I face the same issue with prometheus-operator chart - helm-diff provides diff for 1 generated List object only. 
 F.e. I have both `additionalPrometheusRules`, `additionalServiceMonitors` configured and changed. As the result, I get diff output for `additionalPrometheusRules`, but diff for `additionalServiceMonitors` is never produced.

**Comment by mumoshu** [comment]
@robinelfrink @jesussancheztellomm @iivanov1 Hey! Thanks for reporting.

Finally, I got some time to work on this.

So, #232 is the fix, which instructs helm-diff to "flatten" manifests, by moving resources embedded in List resources into the top-level.

Would you mind reviewing/testing it?

**Comment by iivanov1** [comment]
@mumoshu Thank you! v3.1.3 works like a charm!
