### ISSUE TITLE
can't execute 'bash'

### ISSUE THREAD

**Issue by okgolove** [databus23/helm-diff#204]
My case was installing helm-diff to an alpine container without bash.
I go the error from the subject.

As far as I understand this is because of this shebang https://github.com/databus23/helm-diff/blob/master/install-binary.sh#L1

Should we use `/usr/bin/env sh` instead of bash?

**Comment by deiga** [comment]
At least currently it's not POSIX compliant, so using `sh` instead wouldn't work out of the box

**Comment by okgolove** [comment]
@deiga it wouldn't. 
Should we rewrite it? :)

**Comment by deiga** [comment]
There are not that many changes needed and I do prefer POSIX compatibility

**Comment by deiga** [comment]
I made a PR
