### ISSUE TITLE
Issue installing helm-diff with helm 3

### ISSUE THREAD

**Issue by kstephens-** [databus23/helm-diff#205]
I'm working on migrating from helm 2 to helm 3, but I'm running into an issue trying to install the helm-diff plugin with helm 3 (specifically helm 3.1.2). I may be missing something, but I think this might be a bug, and I didn't see any issues or PRs addressing this.

When I run
```
helm plugin install https://github.com/databus23/helm-diff
```

The installation fails with
```
Error: unknown command "home" for "helm"
Run 'helm --help' for usage.
Downloading https://github.com/databus23/helm-diff/releases/download/v3.1.1/helm-diff-macos.tgz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   630  100   630    0     0   1327      0 --:--:-- --:--:-- --:--:--  1329
100 12.7M  100 12.7M    0     0  5506k      0  0:00:02  0:00:02 --:--:-- 7335k
Preparing to install into /plugins/helm-diff
cp: /plugins/helm-diff/bin/diff: Permission denied
Failed to install helm-diff
\tFor support, go to https://github.com/databus23/helm-diff.
Error: plugin install hook for "diff" exited with error
```

I investigated a little and it looks like the issue is that install-binary.sh tries to call `helm home`, which has been removed in helm 3. This causes the error in the log above. The result is that HELM_PLUGIN_DIR ends up being empty, which causes the permission denied, since install-binary.sh is then trying to copy files to /plugins/helm-diff/bin/diff.

Let me know if I can help out with this in any way.

**Comment by deiga** [comment]
`helm home` usage has been removed 6 months ago AFAIK
Your error message states that the user you ran the installation with doesn't have permissions to modify `/plugins/helm-diff/bin/diff`
Are you accidentally using root to install the plugin?

**Comment by kstephens-** [comment]
Hi deiga,

 No, I'm not using root to install the plugin. To me it looks like `helm home` is being called in install-binary.sh to get the helm plugins location, which is raising this error:

"""
Error: unknown command "home" for "helm"
"""

The `permission denied` looks like it's being cause by `HELM_PLUGIN_DIR` never being set correctly due to the helm home error, so it's trying to copy the plugin files to a non-existent /plugins directory under the root directory.

I'm trying to install the latest verseion, v3.1.1, by the way. If you look at install-binary.sh, it looks like `helm home` is still being called, on v3.1.1 and master.

Is there another way I have to install the plugin with helm 3, rather than the usual `helm plugin install`?

**Comment by deiga** [comment]
Please note that the line using `helm home` has been commented out.
Have you tried running the command specified in the Readme `helm plugin install https://github.com/databus23/helm-diff --version master`

**Comment by kstephens-** [comment]
I'll try that later today. Ideally, I'd like to be able to pin it to a specific version.

**Comment by kstephens-** [comment]
Looks like it was an issue on my end. I did a clean install of helm 3, removed all caches and plugin artifacts from my previous attempts, and it installs fine. 

I think it was running the 2to3 plugin on my local configuration that led to the problem.

Closing this.
