### ISSUE TITLE
Helm 3 compatibility? Make it clear in README

### ISSUE THREAD

**Issue by max-rocket-internet** [databus23/helm-diff#207]
I understand this plugin is not compatible with Helm 3? Is that correct?

Other issues regarding Helm 3 but unclear:
https://github.com/databus23/helm-diff/issues/205
https://github.com/databus23/helm-diff/issues/180
https://github.com/databus23/helm-diff/issues/170

It would be good to have a loud and clear reference in the README to state whether it is or not 🙂

**Comment by deiga** [comment]
It is compatible with helm 3. If it weren't then that should be mentioned, otherwise the assumption should be that it is compatible with latest version

**Comment by deiga** [comment]
What issue are you encountering that makes you think it isn't compatible?

**Comment by max-rocket-internet** [comment]
> If it weren't then that should be mentioned

OK but in the README there is mentions of Helm version `> 2.3.x`, which I know would include version 3 but version 2.3 is sooo old, it kinda makes me think this plugin is not made for recent versions of Helm.

But OK, I will close this issue.

> What issue are you encountering that makes you think it isn't compatible?

The diff is not fully shown to include reverting manual changes in the cluster. In Helm2 this didn't matter but in Helm3 it's very important due to the new 3-way merge process. It's this actually issue: https://github.com/databus23/helm-diff/issues/176
