### ISSUE TITLE
Error: unknown flag: --repo

### ISSUE THREAD

**Issue by dewnull** [databus23/helm-diff#213]
I get an error when  I use --repo option

Error: unknown flag: --repo

```bash
helm diff upgrade -n my release chart --repo https://url.io  --reuse-value --set value=value
```

My workaround is to add the repo to them using
``` bash
helm repo add aName https://url.io 
```

helm v3.2.1
diff  v3.1.1

**Comment by davidholsgrove** [comment]
I have the same request - passing the `--repo` makes this a one liner

**Comment by jasonstitt** [comment]
This is important for automated workflows. `helm repo add` is stateful - changes config on host system - which is undesirable for a step in an automated process to do without input.

**Comment by cwrau** [comment]
This is still needed, please reopen

**Comment by pnathan** [comment]
Agreed - as per @jasonstitt 's remark, this is a significant bug in workflows.
