### ISSUE TITLE
helm diff upgrade will now show live-state changes

### ISSUE THREAD

**Issue by strainovic** [databus23/helm-diff#215]
Hi all,

I love this plugin and I use it every day. It is really great.

I'm not sure if it is possible to get a diff between release, live-state, and upgrade?

For example:

I have some variable set to `1`. I deploy it. Later on, somebody changes it through kubectl to `2`. Then I change it to `3`. If I run helm diff upgrade, I'll see only change from `1` to `3` which is not correct. I have to know if somebody changed it to `2` to check with him before I do upgrade.

Any suggestion?

Thanks!

**Comment by max-rocket-internet** [comment]
It's not possible unfortunately, refer to https://github.com/databus23/helm-diff/issues/176
