### ISSUE TITLE
Consider various output options when executing a diff

### ISSUE THREAD

**Issue by jtslear** [databus23/helm-diff#222]
For some helm releases, a simple upgrade can change nearly every file as some helm charts put the version as a label or annotation for every object that gets created.  This makes diff outputs a very boring read.  Similar to https://github.com/databus23/helm-diff/pull/221 it be neat if we could ask the plugin for various options to better our format to make it easier for review.  

Things to consider:

* Output that only shows what objects were changed
* ~~Output similar to `git diff` where it shows just the immediate changes of an object, vs output the ENTIRE object~~
* Output in a programmatic format (as mention in https://github.com/databus23/helm-diff/pull/221) such that we can parse and do fun scriptable things with it.

**Comment by deiga** [comment]
Did you consider that `helm diff -C5 ...` already "solves" at least your second point

**Comment by jtslear** [comment]
:astonished: I had no idea this option existed.  Thank you for that :fire: tip.  The rest of my proposal still stands, so I will not yet close this issue.
