### ISSUE TITLE
Helm diff suppress is not working and --suppress makes the helm diff command to stuck for ever

### ISSUE THREAD

**Issue by ronyjoy** [databus23/helm-diff#234]
I couldn't make the helm diff suppress to work , can any one paste a working example. I tried the following in the helm diff but as soon as i add --suppress the command never finish it is stuck for ever

--suppress Secret.data=[create_vhosts]

**Comment by mumoshu** [comment]
@ronyjoy Hey. You can only suppress by kinds so it should look like e.g. `--suppress ConfigMap`.

Also, you can use `--suppress-secrets` which is basically `--suppress Secret` if all you want is to suppress diff on secrets

**Comment by ronyjoy** [comment]
ohh ok , got it , With just Kind as below it is stuck noout put 

helm diff upgrade gwaf charts/gwaf --suppress Secret
--

**Comment by mumoshu** [comment]
@ronyjoy If it hangs, I guess it might be due to that you have no proper access to either chart repository or K8s API server.

**Comment by ronyjoy** [comment]
hmm interesting , with out --suppress it works fine always

**Comment by mumoshu** [comment]
@ronyjoy Thanks! Interesting - I thought there may be any edge case here.

I tried to add multiple `--suppress` to exclude all the Kinds but it still worked fine:

```
$ helm diff upgrade foo stable/envoy --set image.tag=123 --suppress ConfigMap --suppress PodDisruptionBudget --suppress Deployment --suppress Service
default, envoy, Service (v1) has changed:
+ Changes suppressed on sensitive content of type Service
default, foo-envoy, ConfigMap (v1) has changed:
+ Changes suppressed on sensitive content of type ConfigMap
default, foo-envoy, Deployment (apps) has changed:
+ Changes suppressed on sensitive content of type Deployment
default, foo-envoy, PodDisruptionBudget (policy) has changed:
+ Changes suppressed on sensitive content of type PodDisruptionBudget
default, foo-envoy-xds, ConfigMap (v1) has changed:
+ Changes suppressed on sensitive content of type ConfigMap
```

Do you have any idea on if you're using helm-diff/helm in a "special" way? I'm using helm v3.2.1 and the latest helm-diff, btw.

**Comment by ronyjoy** [comment]
nothing special , but my helm version is 3.2.0 , let me update it.

**Comment by mumoshu** [comment]
@ronyjoy Assuming helm and your K8s are both fine, the only suspicious point is probably your chart? If you could agree, I appreciate it if you could share your `charts/test` used in the above test.

**Comment by mumoshu** [comment]
Also- would u mind sharing log output when you provider `--debug` flag to helm, like `helm --debug diff upgrade (OTHER ARGS)`?

**Comment by ronyjoy** [comment]
@mumoshu I have updated to helm 3.3.0 and it started working. But I don't it was an issue with 3.2.0 , it was just the Kubernetes connection lost / something in those lines , Thanks a lot for your help.

**Comment by mumoshu** [comment]
Thanks for confirming! I'm closing this as resolved.
