### ISSUE TITLE
Proposal: Show suppressed Secret data keys under an optional flag

### ISSUE THREAD

**Issue by ClementFelipe** [databus23/helm-diff#235]
Within a secret, when using the `-q` (`--suppress-secrets`) flag, a way to visualize the name of keys whose values have been altered. This could perhaps be done with an additional `--show-suppressed-keys` flag.

Example (current):

```sh
> helm diff upgrade -q ... 
my-namespace, my-secret, Secret (v1) has changed:
+ Changes suppressed on sensitive content of type Secret
```

Example (proposal):

```sh
> helm diff upgrade -q --show-suppressed-keys ... 
my-namespace, my-secret, Secret (v1) has changed:
# Source: templates/secret.yaml
apiVersion: v1
data:
- FOO: <suppressed-data>
+ FOO: <suppressed-data>
  BAR: <suppressed-data>
  BAZ: <suppressed-data>
kind: Secret
metadata:
  annotations:
    meta.helm.sh/release-name: my-release
    meta.helm.sh/release-namespace: my-namespace
  creationTimestamp: "2020-06-17T22:32:40Z"
  labels:
    app.kubernetes.io/managed-by: Helm
  name: my-secret
  namespace: my-namespace
  resourceVersion: "12345678"
  selfLink: /api/v1/namespaces/my-namespace/secrets/my-secret
  uid: ab13ee8c-b278-42f6-a38e-7c8cc8329c57
type: Opaque
```

This could be useful in cases where secret key names are not sensitive, and there is a need to check wether a keys value was modified effectively while also suppressing it.

I could take a crack at a PR if this proposal seems reasonable.

**Comment by mumoshu** [comment]
@ClementFelipe Hey! Thanks for the proposal. I believe this is a great addition to helm-diff.

Although it may look like a tiny detail - I'd probably prefer `--suppress-secret-data-values`(btw does this sound natural? I'm not a great English writer/reader 😃 ), so that it can be a bit easier to implement/use because it's just one flag to enable this feature.

WDYT?

**Comment by databus23** [comment]
This is already implemented on be default, no?

**Comment by ClementFelipe** [comment]
Don't know how I missed that... I'll go ahead and close this then. 😬

**Comment by mumoshu** [comment]
@databus23 Thanks! I never realized we already had that. I'm feeling like I found a hidden easter egg. Great job 😄
