### ISSUE TITLE
Failed to create the file /tmp/helm-diff.tgz: Permission denied

### ISSUE THREAD

**Issue by mozai** [databus23/helm-diff#241]
This happens with both helm v2.14.3 and v3.3.0

Steps to reproduce:

    touch /tmp/helm-diff.tgz
    chmod 000 /tmp/helm-diff.tgz
    helm plugin install https://github.com/databus23/helm-diff

Expected results:

    helm downloads the appropriate tarball, unpackages it, puts the contents in their places in $HOME/.helm/
    helm removes the temporary file that was downloaded after using it

Seen instead:

Warning: Failed to create the file /tmp/helm-diff.tgz: Permission denied
curl: (23) Failed writing body (0 != 16360)
Failed to install helm-diff

The "Steps to reproduce" are a contrived scenario, but I encountered it naturally when working on a machine I share with other users. In my case, another user launched helm plugin install weeks before I did.

Workaround:
    sudo rm /tmp/helm-diff.tgz

Subsequent problem:

    tar: diff/LICENSE: Cannot open: File exists
    tar: diff/bin: Cannot utime: Operation not permitted
    tar: diff/plugin.yaml: Cannot open: File exists
    tar: diff/README.md: Cannot open: File exists
    tar: diff/bin/diff: Cannot open: File exists
    tar: diff: Cannot utime: Operation not permitted
    tar: Exiting with failure status due to previous errors
    Failed to install helm-diff

Workaround step two:

    sudo rm -rf /tmp/helm-diff/

**Comment by theAkito** [comment]
> chmod 000 /tmp/helm-diff.tgz

When does that ever happen without someone doing it on purpose and knowing what it will cause?

**Comment by mozai** [comment]
You should read the rest of the message.

> The "Steps to reproduce" are **a contrived scenario**, but I encountered it naturally when working on **a machine I share with other users**. In my case, another user launched helm plugin install weeks before I did.

Nobody did `chmod 000`: it's a more efficient way to reproduce the problem. I won't assume the devs share their computers with co-workers then can use for a more authentic steps-to-reproduce -- if they did, I'm certain they've already seen this problem.

**Comment by mozai** [comment]
You should read the rest of the message.

> The "Steps to reproduce" are **a contrived scenario**, but I encountered it naturally when working on **a machine I share with other users**. In my case, another user launched helm plugin install weeks before I did.

Nobody did `chmod 000`.  It was a more succinct and single-user way of reproducing the scenario I naturally encountered.

* User A installs the plugin in their account
* User B tries to install the plugin, 
* ... can't because the files /tmp/helm-diff.tgz is stlil on-disk and owned by User A.
* User B does a `sudo rm -f /tmp/helm-diff.tgz` (if they have root access), tries again.
* ... can't because /tmp/helm-diff/ is still on-disk and owned by User A.

**Comment by theAkito** [comment]
> You should read the rest of the message.

I usually read the message I respond to several times, as I did here, but it still did not clear up the question I had.

Basically, what you want is that the installation cleans up after themselves?

**Comment by mozai** [comment]
Deleting temp files when they're no longer needed would be ideal.  Even better would be [using temp files](https://github.com/databus23/helm-diff/blob/master/install-binary.sh#L89) that other users on the same system [won't try to write into](https://github.com/databus23/helm-diff/blob/master/install-binary.sh#L101), as two users trying to install at the same time could cause lockouts, or worse a later process could truncate a file just as an earlier process tries to read it.  (I know it's unlikely but it happens and it is preventable.)

If I install helm-diff, I believe that shouldn't prevent all other users on the same machine from installing helm-diff.

**Comment by deiga** [comment]
@mozai Are you sure this issue belongs here? Isn't this issue related to `helm plugin install` and it's behaviour?

**Comment by mozai** [comment]
@deiga No it's helm-diff that writes the temp files, and errors-out if they can't write to the temp file because someone else already installed helm-diff.  Look at the two links I included in my last comment.

**Comment by mozai** [comment]
Just because nobody's made comments doens't mean the issue is resolved.

**Comment by zzbennett** [comment]
+1 this is pretty annoying. Not having root access myself on our jump box, I have to get an admin to sudo rm the /tmp/helm-diff file whenever I try to install the plugin and another user has already installed it on the same machine. we are upgrading to helm 3 and all users are having to re-install the plugin, but we keep running into this issue.

**Comment by keymon** [comment]
Trying to fix this in #269

**Comment by neo773** [comment]
Hi, I just ran into the exact same issue why has the commit not been merged into master yet?

**Comment by mozai** [comment]
Just because nobody's made comments doens't mean the issue is resolved.

**Comment by keymon** [comment]
Exactly #269 did fix it but was never merged :(

**Comment by keymon** [comment]
Sent the PR again in #301 :crossed_fingers:

**Comment by keymon** [comment]
Exactly
-- 
Héctor Rivas
