### ISSUE TITLE
diff does not honour "helm.sh/resource-policy: keep" 

### ISSUE THREAD

**Issue by timjohncurtis** [databus23/helm-diff#246]
We have a deployment which used an older version of helm, which defines the namespace as a YAML object in the helm chart. We want to upgrade to removing this as is the defined method in helm 3, so have added `helm.sh/resource-policy: keep` as an annotation, however when I run `helm diff` on the chart, it shows it will be removed. This is intended functionality as the YAML no longer exists, but could a note be added to the output of the diff noting to the user that this is annotated so it will not be deleted?

**Comment by chudyandrej** [comment]
I have the same problem.

**Comment by ncronquist** [comment]
I also just ran into this. I know it may be kind of an edge case, but it might be worth re-opening.
