### ISSUE TITLE
Helm diff release “Error: unknown flag: --template”

### ISSUE THREAD

**Issue by rahulwagh** [databus23/helm-diff#247]
I was trying to use helm plugin `diff` but when I was trying to find the diff between the release it is throwing me an error 

Here is my **helm diff command**

```
helm diff release myhelloworld myhelloworld2
```

```
Error: unknown flag: --template

Error: plugin "diff" exited with error
```

Here are my **releases**

```
helm list -a
```

```
NAME         	NAMESPACE	REVISION
myhelloworld 	default  	3       
myhelloworld2	default  	1       
```

Is there anything wrong with my **helm diff** command ?

**Comment by capathida** [comment]
Just as a first glance, it seems like in the function:
func getChart(release, namespace string) (string, error) {
	args := []string{"get", release, "--template", "{{.Release.Chart.Name}}"}

seems to be missing "all" or some other {command}
so perhaps
args := []string{"get", "all", release, "--template", "{{.Release.Chart.Name}}"}

**Comment by lgutter** [comment]
I'm having the exact same issue with Helm `v3.4.2`. `helm diff version` just shows `HEAD`.
Any idea on if this will get fixed any time soon?

**Comment by mayconfsbrito** [comment]
I have this problem as well:
```
% helm diff release -n play-01-27118321-review-spx-auto-d-ievaa8 review-spx-auto-d-ievaa8 spx-auto-deploy-app-play
Error: exit status 1: Error: unknown flag: --template
```

**Comment by fffffreedom** [comment]
me too, anyone focus on this ?

**Comment by jjjjeeffff** [comment]
Seeing this issue in helm 3.7.0.
