### ISSUE TITLE
Build for Apple Silicon (macos-arm64)

### ISSUE THREAD

**Issue by njoniec** [databus23/helm-diff#262]
Plugin install fails on ARM-based Macs. I was able to build from source and copy the executable to my helm plugins directory.

I am using helm 3.5.2 and helmfile 0.138 from Homebrew.

```
nick@macbook-air ~ % helm plugin install https://github.com/databus23/helm-diff
No prebuild binary for macos-arm64.
Failed to install helm-diff
	For support, go to https://github.com/databus23/helm-diff.
Error: plugin install hook for "diff" exited with error
```

**Comment by f3lan** [comment]
Hi @njoniec

Maybe you can try this fix an check out if it works on your machine too:

https://github.com/databus23/helm-diff/pull/264

Cheers,
f3lan

**Comment by nightofmind** [comment]
> Hi @njoniec
> 
> Maybe you can try this fix an check out if it works on your machine too:
> 
> #264
> 
> Cheers,
> f3lan

how to do it? Check it out and build it locally?

**Comment by atassis** [comment]
@nightofmind install plugin locally, checkout the PR, and then in plugin directory run `helm plugin install .`
For a record: https://helm.sh/docs/topics/plugins/#installing-a-plugin

**Comment by f3lan** [comment]
@njoniec 
Alternatively you can install the plugin via the url: `helm plugin install https://github.com/f3lan/helm-diff`.

I did the small fix on my forked master too.

But the solution of @atassis is perfectly fine as well.

**Comment by petrukngantuk** [comment]
anyway I manage to install helm-diff plugins in the m1 macos-arm64 with : 

```
brew install helm
gh repo clone databus23/helm-diff
cd helm-diff

```

change `install-binary.sh` line 58 to

```
  supported="linux-amd64\nfreebsd-amd64\nmacos-amd64\nmacos-arm64\nwindows-amd64"
```

```
go mod vendor
make install/helm3
```

**Comment by atassis** [comment]
Thinking about making a fork it finding a proper one, though u don't know golang 👀 but she to support open source

**Comment by ypicard** [comment]
Any news on this?

**Comment by petrukngantuk** [comment]
> I've compiled helm-diff using the approach mentioned above, but diff can't show colored output. Possible anyone meets with this and know a solution?

What go version did you use? $GOPATH already correct?
