### ISSUE TITLE
version update issue

### ISSUE THREAD

**Issue by jeff-knurek** [databus23/helm-diff#27]
My CI has suddenly broke when running `helm diff`

+ `helm version`
```
Client: &version.Version{SemVer:"v2.7.2", GitCommit:"8478fb4fc723885b155c924d1c8c410b7a9444e6", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.7.0", GitCommit:"08c1144f5eb3e3b636d9775617287cc26e53dba4", GitTreeState:"clean"}
```
+ `helm plugin install https://github.com/databus23/helm-diff --version v2.7.0+1`
```
Downloading https://github.com/databus23/helm-diff/releases/download/v2.8.0%2B1/helm-diff-linux.tgz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   609    0   609    0     0    609      0 --:--:-- --:--:-- --:--:--  1208
 32 4419k   32 1443k    0     0   481k      0  0:00:09  0:00:03  0:00:06  714k
 72 4419k   72 3195k    0     0   798k      0  0:00:05  0:00:04  0:00:01 1060k
100 4419k  100 4419k    0     0  1104k      0  0:00:04  0:00:04 --:--:-- 1266k
Preparing to install into /home/jenkins/.helm/plugins/helm-diff
helm-diff installed into /home/jenkins/.helm/plugins/helm-diff/helm-diff
Show a diff explaining what a helm upgrade would change.

This fetches the currently deployed version of a release
and compares it to a local chart plus values.
This can be used visualize what changes a helm upgrade will
perform.

Usage:
  diff [flags] [RELEASE] [CHART]

Flags:
      --no-color               remove colors from the output
      --reuse-values           reuse the last release's values and merge in any new values
      --set stringArray        set values on the command line (can specify multiple or separate values with commas: key1=val1,key2=val2)
      --suppress stringArray   allows suppression of the values listed in the diff output
  -q, --suppress-secrets       suppress secrets in the output
  -f, --values valueFiles      specify values in a YAML file (can specify multiple) (default [])
  -v, --version                show version
Installed plugin: diff
```
+ `helm plugin list`
```
NAME	VERSION	DESCRIPTION                           
diff	2.7.0+1	Preview helm upgrade changes as a diff
```
+ `helm diff -f values.yaml production .`
```
Error: incompatible versions client[v2.8.0] server[v2.7.0]
Usage:
  diff [flags] [RELEASE] [CHART]

Flags:
      --no-color               remove colors from the output
      --reuse-values           reuse the last release's values and merge in any new values
      --set stringArray        set values on the command line (can specify multiple or separate values with commas: key1=val1,key2=val2)
      --suppress stringArray   allows suppression of the values listed in the diff output
  -q, --suppress-secrets       suppress secrets in the output
  -f, --values valueFiles      specify values in a YAML file (can specify multiple) (default [])
  -v, --version                show version

Error: plugin "diff" exited with error
```

**Comment by databus23** [comment]
> incompatible versions client[v2.8.0] server[v2.7.0]
That pretty much explains it. The latest version of helm-diff is imports helm version 2.8.0.
This requires the server/tiller to be at least at the same version. While tiller can cope with older clients the other way around is not the case unfortuantely.

You have to options:
* revert to the prevision `helm-diff` version
*upgrade tiller to the latest version

**Comment by jeff-knurek** [comment]
but `helm plugin install --help`
indicates:
```
Usage:
  helm plugin install [options] <path|url>... [flags]

Flags:
      --version string   specify a version constraint. If this is not specified, the latest version is installed
```
I'm specifically trying to revert to the older version, but that still doesn't work:
see above: `helm plugin install https://github.com/databus23/helm-diff --version v2.7.0+1`

**Comment by databus23** [comment]
I was not aware that you can specify a version when installing a plugin.

I think the install script referenced in the plugin.yaml is not handling that case and always installs latest: https://github.com/databus23/helm-diff/blob/master/install-binary.sh

**Comment by databus23** [comment]
I can't find documentation on how this is supposed to work. Looking at https://github.com/technosophos/helm-template/blob/master/install-binary.sh#L69 (Where I copied the install script from) it seems the me this plugin would still exhibit the same behavior.
Looking at the plugin installer code it seems to checkout the tag specified with `--version`, so the install script maybe should use something like `git describe --tags` to get the requested release.

But this can't be fixed for older releases as the install script will still be the old one when checking out `v2.7.0+1`...

**Comment by databus23** [comment]
I fixed the installer script but this will only work for versions yet the be released. 

In your case you need to either upgrade tiller or install the plugin manually.

**Comment by databus23** [comment]
Seems like this is resolved. The general problem is that `helm diff` is compiled with a certain version of the helm client and can't talk to tiller versions that have a smaller version.

This can be fixed by either upgrading tiller or downgrading `helm diff`.  `helm plugin install --version $VERSION` should work for versions`v2.8.0+1` and up
