### ISSUE TITLE
Concise diff

### ISSUE THREAD

**Issue by z0rc** [databus23/helm-diff#274]
Running diff when working with relatively big charts, like [kube-prometheus-stack](https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack) sometimes produces output with thousands of lines (all hail CRDs). This makes verifying the changes a cumbersome task, where I need to actively look for real changes.

Would it be possible to make diff output concise, by compacting unchanged lines and showing only the parts that matter? Terraform did this recently https://www.hashicorp.com/blog/terraform-0-14-adds-a-new-concise-diff-format-to-terraform-plans, git was doing this since inception, etc.

**Comment by z0rc** [comment]
Yeah, `--context` is what git does by default. Still, I'm more interested to see diff in a way how terraform does it, by collapsing unchanged branches, while changed branches are visible under parent tree structure. As helm-diff is used only from yamls, terraform style concise diff is more preferred.

**Comment by z0rc** [comment]
I'd like to hear maintainers' option prior to closing it.

**Comment by z0rc** [comment]
Still waiting.

**Comment by mumoshu** [comment]
I think the notion of concise-diff is specific to Terraform and HCL and there's no straight-forward interpretation of it in YAML/helm-diff's context.
I'm open to concrete suggestions/pull requests to add it so that I can see if it really makes sense/worth the effort. But please let me close this as unactionable. Sorry! But thanks for your feedback.

**Comment by mumoshu** [comment]
A possible way forward would be to you write a concise-diff library for Go and we explore integrating it into helm-diff.
We use `difflib` for Go for diffing so if such library can be a drop-in replacement for difflib it should be easy to experiment.
