### ISSUE TITLE
Add ARM binaries to releases (Plugin install fails on Raspberry Pi)

### ISSUE THREAD

**Issue by markscamilleri** [databus23/helm-diff#275]
I'm trying to install this plugin on my Raspberry Pi (Rasbpian OS), and it can't seem to find any pre-built packages. I'm also trying to build it myself, but I haven't been able to so far

```
No prebuild binary for linux-armv7.
Failed to install helm-diff
        For support, go to https://github.com/databus23/helm-diff.
```

**Comment by markscamilleri** [comment]
Ok I managed to install from source - it would have been great to have some documentation so I went ahead and wrote some. I've opened the PR (#276). I'm not sure if I should close this ticket or maybe we can leave it open if there are plans for the inclusion of an arm binary...

**Comment by mumoshu** [comment]
@markscamilleri Hey! Thanks for reporting and #276. That's super helpful.

Re this issue, let's keep it open until we/someone adds the arm binary build.

I thought we still had no automated release process so it should be a matter of adding some code to [our `make dist` target](https://github.com/databus23/helm-diff/blob/d42b177462211ce1f15db07f6309359818a005f9/Makefile#L62-L73)

**Comment by mumoshu** [comment]
Turns out @dschaaff has kindly submitted a feature request to add ARM binaries #267

**Comment by zoonage** [comment]
Could adding `macos-arm64` support come under this as well or is this focussed on the linux-arm64 target?

**Comment by mumoshu** [comment]
@zoonage Hey! #267 definitely focuses on linux-arm64. If anyone could test and verify that this works on macos-arm64 and contribute the addition to the build target like done in #267, these seems not reason to not support it.

**Comment by rblaine95** [comment]
Not stale - still relevant ❤️
