### ISSUE TITLE
helm diff version only shows 'HEAD'

### ISSUE THREAD

**Issue by mhubig** [databus23/helm-diff#279]
`helm diff version` only shows 'HEAD' ... :-(

**Comment by mumoshu** [comment]
@mhubig Hey! Thanks for reporting.

That's really interesting, as we do have our Makefile to set it on build

https://github.com/databus23/helm-diff/blob/master/Makefile#L7
https://github.com/databus23/helm-diff/blob/0882d8c63d782cd5ac325fe3b4e00342ae30f6a1/Makefile#L65
https://github.com/databus23/helm-diff/blob/master/cmd/version.go#L10
