### ISSUE TITLE
Can't enable colors back

### ISSUE THREAD

**Issue by dex4er** [databus23/helm-diff#281]
Please revert 0c4bd341ab8f3a5135248d5794ea522c92151d06

I run helm diff in the CI/CD pipeline and I miss the color output from helm diff now. Actually even running it through "grep" on the console with the colors were useful. Then this change is a regression for me.

Maybe you can introduce some addtional option like "--color" or "--force-color" instead?

**Comment by dex4er** [comment]
OK I see it was PR #240 that made this regression.

**Comment by mumoshu** [comment]
@deiga Thanks for reporting! "Regression" sounds like a strong word though.

@misberner WDYT? I think adding another flag `--color` to force color might be a good idea. I'm not yet convinced this is a regression and the PR/commit can just be reverted.

**Comment by mumoshu** [comment]
@dex4er Thanks for reporting! "Regression" sounds like a strong word though.

@misberner WDYT? I think adding another flag `--color` to force color might be a good idea. I'm not yet convinced this is a regression and the PR/commit can just be reverted.

**Comment by dex4er** [comment]
Oh I didn't realise there is modern flamewar between color and no-color. Now I found https://no-color.org/ with reasonable proposition that NO_COLOR envvar should disable ANSI codes.

Detection of the terminal is not enough unfortunately because I use `helm diff` explicitely in CI/CD context and it is detected as non-terminal and has `TERM=dumb` envvar set. Then seeing a colors in the report file is very useful to quickly verify the changes in the new deployments then I'm very satisfied with original helm diff's feature.

Well, "regression" looked like neutral word for me and it might be described as "feature which doesn't work in newer version anymore" 😄

**Comment by misberner** [comment]
It's a bit indirect, but you _can_ get the old behavior via `--no-color=false`. Does this not work?

**Comment by dex4er** [comment]
I can confirm `--no-color=false` works. Looks maybe a little ackward but at least it produces correct output in CI/CD context. Thanks a lot!

**Comment by mumoshu** [comment]
Thank you everyone for sharing valuable feedback!

When I wrote my first response in this thread, I didn't know that `TERM=dumb` was used that way. I now believe helm-diff should just disable colors when `TERM=dumb`. For @dex4er's case, it looks like your CI did set a correct `TERM` so I'd say it's definitely helm-diff's fault that it didn't respect it(to disable colors).

I'm going to create a PR shortly.
