### ISSUE TITLE
Please release new version of this plugin

### ISSUE THREAD

**Issue by dex4er** [databus23/helm-diff#293]
Hi. If I install with `helm plugin install` then still I have old, unfixed version. Could you make a new Github release, please?

**Comment by dex4er** [comment]
@mumoshu are you able to prepare new release?

**Comment by mahgo** [comment]
This would be great! Currently having to use a manual build to be able to have https://github.com/databus23/helm-diff/commit/3ce490ed30de63a4d79b2a2b79d3c00204772f21

**Comment by arbourd** [comment]
I am willing to help maintain this if help is needed! ❤️

**Comment by mumoshu** [comment]
3.2.0 has been released yesterday. Closing as resolved!
