### ISSUE TITLE
Add support for --create-namespace and --wait

### ISSUE THREAD

**Issue by aschleifer** [databus23/helm-diff#298]
Please add support for `--create-namespace` and `--wait` from helm3 into helm diff.

Currently these flags are not usable because helm diff will exit with "unknown flags" errors.

**Comment by anthraxx** [comment]
bump

**Comment by mumoshu** [comment]
We had a related discussion at #278 that we basically don't want to add "placeholder" flags just to make a specific use-case(I think you're trying to pass all the args passed to helm-template to helm-diff, right?)

That's not the end of the story though.
We've added `HELM_DIFF_IGNORE_UNKNOWN_FLAGS` option which can be used to ignore that unkown-flag errors.
See #278 and please report back if it doesn't work for you. Thanks!
