### ISSUE TITLE
helm-diff  return no diff  when  helm chart  status  is failed

### ISSUE THREAD

**Issue by tanguofu** [databus23/helm-diff#306]
when a installed helm chart  update failed，helm diff cannot show diffs

**Comment by tanguofu** [comment]
any hlepers here？

**Comment by andrewnazarov** [comment]
This behaviour started being annoying for us. Don't know if it's even possible to do anything with it, because it's how Helm works - it writes all resource information in the secret even when the installation fails.

**Comment by mumoshu** [comment]
@tanguofu @andrewnazarov I verified that `--three-way-merge` added via #304 fixes this issue. Closing as resolved. Probably it will be released as part of 3.3.0. In the meantime, please build helm-diff from the latest master if you're eager to test it early. Thanks!
