### ISSUE TITLE
Helm diff shows functionally equivalent yaml as diff

### ISSUE THREAD

**Issue by jonerer** [databus23/helm-diff#310]
Hello, thanks for a great project! It's an indispensable part of my helm work flow

Recently I've been using a component that applies helm charts on my behalf in a GitOps flow (Flux) and it's causing some issues with how `helm diff` works. More specifically it alters the yaml a bit from the template rendering.

For instance we get diffs like this:

```
            ports:
-             - name: http
-               containerPort: 80
+             - containerPort: 80
+               name: http
                protocol: TCP
```

In this case it just moved around some attributes in a mapping

It would be great if `helm diff` could overlook these changes, since they are functionally equivalent. Perhaps by adding a `--normalize` parameter or so?

**Comment by jonerer** [comment]
Would it make sense to add a `--normalize` parameter that uses `yq` to pretty-print the output before diffing? Exactly like the example here: https://mikefarah.gitbook.io/yq/usage/tips-and-tricks#comparing-yaml-files

**Comment by jonerer** [comment]
I had a look in the source code and it seems like it's already been implemented, awesome! https://github.com/databus23/helm-diff/commit/3ce490ed30de63a4d79b2a2b79d3c00204772f21

But doesn't seem to be included in a release yet. Any thoughts on when we can see a release? :) @mumoshu

**Comment by mumoshu** [comment]
3.2.0 includes the normalize option. Closing as resolved!
