### ISSUE TITLE
Use exit status code to indicate any differences were found.

### ISSUE THREAD

**Issue by FuyuanChu** [databus23/helm-diff#311]
It is a super useful plugin for our Gitops automation.

Need a simple approach for a shell script to find out it has differences or not after running helm diff.

Just like the way `kubectl diff` does:

```
Exit status: 0 No differences were found. 1 Differences were found. >1  with an error.
```

Many thanks.

**Comment by mumoshu** [comment]
@FuyuanChu Hey! Try `-detailed-exitcode` for that 😃 

```
--detailed-exitcode      return a non-zero exit code when there are changes
```
