### ISSUE TITLE
Issue new release

### ISSUE THREAD

**Issue by PPACI** [databus23/helm-diff#312]
Hi.
The latest release version is more than 1 year ago.

The main branch of this repo contains a lot of useful feature that are not available in the release.
In my company, we would need to use the `helm diff upgrade --repo` to use internal charts (without using `helm repo add`).

Would it be possible to issue a new release? Even if it's flagged as beta.

Thank you in advance for this super useful project!

**Comment by day1118** [comment]
@databus23 - can you please release a new version?
Thanks

**Comment by mumoshu** [comment]
I've cut 3.2.0 today! Closing as resolved.
