### ISSUE TITLE
Downloading  curl: (3) <url> malformed

### ISSUE THREAD

**Issue by arunseth** [databus23/helm-diff#314]
when I try to install helm diff after 3 times I am getting below error, can anyone suggest solution please

Downloading 
curl: (3) <url> malformed
Failed to install helm-diff
	For support, go to https://github.com/databus23/helm-diff.
Error: plugin install hook for "diff" exited with error

**Comment by wu0407** [comment]
```
 bash -x  .local/share/helm/plugins/helm-diff/install-binary.sh
+ PROJECT_NAME=helm-diff
+ PROJECT_GH=databus23/helm-diff
+ export GREP_COLOR=never
+ GREP_COLOR=never
++ '' version --client --short
.local/share/helm/plugins/helm-diff/install-binary.sh: line 9: : command not found
++ awk -F . '{print $1}'
+ HELM_MAJOR_VERSION=
++ '' home --debug=false
.local/share/helm/plugins/helm-diff/install-binary.sh: line 11: : command not found
+ : /plugins/helm-diff
+ type cygpath
+ '[' '' = 1 ']'
+ trap fail_trap EXIT
+ set -e
+ initArch
++ uname -m
+ ARCH=x86_64
+ case $ARCH in
+ ARCH=amd64
+ initOS
++ uname
++ tr '[:upper:]' '[:lower:]'
+ OS=linux
+ case "$OS" in
  verifySupported
+ supported='linux-amd64\nfreebsd-amd64\nmacos-amd64\nwindows-amd64'
+ echo 'linux-amd64\nfreebsd-amd64\nmacos-amd64\nwindows-amd64'
+ grep -q linux-amd64
+ type curl
+ getDownloadURL
++ git -C /plugins/helm-diff describe --tags --exact-match
++ :
+ version=
+ '[' -n '' ']'
+ url=https://api.github.com/repos/databus23/helm-diff/releases/latest
+ type curl
++ curl -s https://api.github.com/repos/databus23/helm-diff/releases/latest
++ grep linux
++ awk '/\"browser_download_url\":/{gsub( /[,\"]/,"", $2); print $2}'
+ DOWNLOAD_URL=
+ downloadFile
+ PLUGIN_TMP_FILE=/tmp/helm-diff.tgz
+ echo 'Downloading '
Downloading 
+ type curl
+ curl -L '' -o /tmp/helm-diff.tgz
curl: (3) <url> malformed
+ fail_trap
+ result=3
+ '[' 3 '!=' 0 ']'
+ echo 'Failed to install helm-diff'
Failed to install helm-diff
+ printf '\tFor support, go to https://github.com/databus23/helm-diff.\n'
        For support, go to https://github.com/databus23/helm-diff.
+ exit 3
```

**Comment by arunseth** [comment]
@wu0407  you want me to replace install-binary.sh with what you shared above? 
I copied helm-diff in my repo but it is still pointing to this repo, replaced databus23 with my repo still pointing this repo

**Comment by wu0407** [comment]
you can edit this script to debug.

**Comment by arunseth** [comment]
In my local it is always using https://github.com/databus23/helm-diff/ url not my git code, I can't edit it so

**Comment by mumoshu** [comment]
I think it's that installing from the latest has been failing badly when you have some GitHub API issue. #285 fixed that so that there's more likely a valid URL passed to `curl` which should prevent a `curl: (3) URL using bad/illegal format or missing URL` or `curl: (3) malformed` error.

Closing as resolved. Please create another issue you still see this problem! Don't forget to include os/arch info when you're doing so. Thanks.

I'm also linking this to https://github.com/databus23/helm-diff/issues/265#issuecomment-1008254066, which is very similar.
