### ISSUE TITLE
Windows Helm Diff path issue

### ISSUE THREAD

**Issue by sbugalski** [databus23/helm-diff#316]
Hello,

I've just found Helm Diff and installed on my Windows 10 pc using `helm plugin install https://github.com/databus23/helm-diff`

Calling `helm diff` from terminal ends like this
```
helm diff
Error: exec: "C:\\Users\\sb\\AppData\\Roaming\\helm\\plugins\\helm-diff/bin/diff": file does not exist
```

Helm installed from Chocolatey
```
helm plugin list
NAME    VERSION DESCRIPTION
diff    3.1.3   Preview helm upgrade changes as a diff


helm version
version.BuildInfo{Version:"v3.7.1", GitCommit:"1d11fcb5d3f3bf00dbe6fe31b8412839a96b3dc4", GitTreeState:"clean", GoVersion:"go1.16.9"}
```

**Comment by srilumpa** [comment]
I also have the following error while installing the plugin in version 3.1.3:

```powershell
> helm plugin install https://github.com/databus23/helm-diff
Error: exec: "sh": executable file not found in %PATH%
```

**Comment by srilumpa** [comment]
To install the help-diff plugin on Windows:

1. download the latest release built for Windows (currently: [version 3.1.3](https://github.com/databus23/helm-diff/releases/download/v3.1.3/helm-diff-windows.tgz))
2. extract the archive
3. copy the content of the `diff` extracted folder to `$APPDATA$\helm\plugins\helm-diff`
4. check if its properly recognized by helm using `helm.exe diff version` (for example)

**Comment by DaWy** [comment]
> To install the help-diff plugin on Windows:
> 
> 1. download the latest release built for Windows (currently: [version 3.1.3](https://github.com/databus23/helm-diff/releases/download/v3.1.3/helm-diff-windows.tgz))
> 2. extract the archive
> 3. copy the content of the `diff` extracted folder to `$APPDATA$\helm\plugins\helm-diff`
> 4. check if its properly recognized by helm using `helm.exe diff version` (for example)

Not working for me. Its saying the same as OP:

![image](https://user-images.githubusercontent.com/1610889/146216094-df1442b4-cbfe-4418-9286-5f279bfdcefd.png)

**Comment by srilumpa** [comment]
That's because there is a space in your path. Check your helm configuration or the plugin's one to identify and fix the issue, but I don't know how to do this

**Comment by mumoshu** [comment]
As @srilumpa has mentioned in the prev comment, https://github.com/helm/helm/issues/7117 seems to indicate that helm plugins isn't supported on Windows (yet).

In the meantime, you would be able to run the plugin directly, by cloning the repo and running `go build .` to build a executable named `helm-diff`, which can be run directly by providing some envvars that are normally populated by helm, like

```
HELM_NAMESPACE=default HELM_BIN=helm ./helm-diff upgrade -h
```

Let me close this as answered and there isn't actionable from the helm-diff side. But please feel free to report back here if the direct run workaround doesn't work.

**Comment by alastairs** [comment]
I had a need to run helm-diff as part of a helmfile deployment, which wasn't able to use the direct run workaround. I was able to resolve this by copying the built `helm-diff.exe` to `%APPDATA%\helm\plugins\helm-diff\bin\diff.exe`. YMMV. 

I don't really understand all the moving parts here, but given a Windows build is published in the latest release and other helm plugins have managed to support Windows installation (e.g. [helm-secrets](https://github.com/jkroepke/helm-secrets)) via `helm plugin install`, perhaps this plugin could too?

**Comment by plain5** [comment]
***My workaround***

* Install `helm-diff` using the `helm plugin` command (do not pay attention to the output errors) : 

```
helm plugin install https://github.com/databus23/helm-diff
```

* Navigate to the `C:\Users\YOUR_USER\AppData\Roaming\helm\plugins\helm-diff` and manually create the `bin` folder.

* Download desired **[release](https://github.com/databus23/helm-diff/releases)** and extract from the archive `diff.exe`.

* Move extracted `diff.exe` inside the `C:\Users\YOUR_USER\AppData\Roaming\helm\plugins\helm-diff\bin` folder.

* Run `helm diff` to verify all work well.

* Happy Diffing!

**Comment by rami-foo** [comment]
I think the support has been added recently so can the plugin add the windows support too?

**Comment by yxxhero** [comment]
ok
