### ISSUE TITLE
No support for --kube-version to set .Capabilities.KubeVersion.Version

### ISSUE THREAD

**Issue by scarby** [databus23/helm-diff#318]
Seemingly helm diff lacks support for any way of specifying which kube-version is in use, it also doesn't honor the version used on the server or client.

desired functionality:
```
helm diff upgrade --kube-version 1.22.4
```
should allow the use of:
```
{{- if semverCompare ">= 1.19.0" $.Capabilities.KubeVersion.Version }}
```

at present  $.Capabilities.KubeVersion.Version seems to be null

**Comment by mumoshu** [comment]
@scarby Hey! Thanks for reporting. I think `Capabilities.KubeVersion` is deprecated and every chart relying on it should migrate to use `Capabilities.ApiVersions.Has` instead. Also, there's no programmatic way to let `helm template` (which we relies on in the no-three-way-merge mode) use arbitrary `Capabilities.KubeVersion` so what you asked is actually impossible.

Probably we'd better add support for `--api-versions`, same as `helm template`. Then you'd migrate your chart to use `ApiVersions.Has`. Does that sound good to you?

**Comment by mumoshu** [comment]
@scarby BTW... are you still using Helm 2? I think it's EOLed in 2020 and `--kube-version` was available only in helm-template for helm v2.
