### ISSUE TITLE
Non deterministic helm diff behavior with "three way merge"

### ISSUE THREAD

**Issue by sbugalski** [databus23/helm-diff#341]
Hello,

I am using helm diff with Azure DevOps pipelines.

Since recent changes we have issue with three way merge non deterministic helm diff and error exit code.

1. ` reading three way merge from env` prints error
![image](https://user-images.githubusercontent.com/45152735/148766510-a019b242-6e1a-4acf-a76e-367907731307.png)

Command:
```bash
  helm diff upgrade \
    --install $RELEASE_NAME ingress-nginx/ingress-nginx \
    --namespace $RELEASE_NAME \
    --version 4.0.6 \
    --values "values.yaml"
```

2. Non deterministic behavior related to `three way merge from env` 
Sometimes same task fails on different pipeline run 
![image](https://user-images.githubusercontent.com/45152735/148766826-e7e5fa9f-08ac-4342-8f11-9022d4bcd070.png)

Same task different results:
![image](https://user-images.githubusercontent.com/45152735/148766914-6e6012c0-b5a1-4ca0-8c65-8b56fbbbb994.png)
![image](https://user-images.githubusercontent.com/45152735/148766928-1cbda442-334a-4a32-991f-5a6971afe99f.png)

Command:
```bash
  HELM_DIFF_THREE_WAY_MERGE=false helm diff upgrade \
    --install $RELEASE_NAME ingress-nginx/ingress-nginx \
    --namespace $RELEASE_NAME \
    --version 4.0.6 \
    --values "values.yaml"
```

**Comment by mumoshu** [comment]
@sbugalski Hey! Thanks for reporting, but I don't get it yet. Are you basically saying that your pipeline step fails whenever helm-diff prints a message (`reading three way merge from env`) to stderr?

`reading three way merge from env` doesn't mean it enabled three-way-merge. It's enabled only when `HELM_DIFF_THREE_WAY_MERGE` is set to `true`. It isn't really an error, but a log message.

**Comment by mumoshu** [comment]
`HELM_DIFF_THREE_WAY_MERGE=false` doesn't suppress the message, but `--three-way-merge` does.
In case what you want is to suppress the message, try:

```
helm diff upgrade \
    --install $RELEASE_NAME ingress-nginx/ingress-nginx \
    --namespace $RELEASE_NAME \
    --version 4.0.6 \
    --values "values.yaml" \
    --three-way-merge=false
```

But again, it doesn't affect the exit code of the command at all. So my guess is that the root cause is in your pipeline step, or perhaps how Azure DevOps pipeline works?

**Comment by sbugalski** [comment]
Thanks @mumoshu 

Wasn't sure how to use the flag, since Docs doesnt say is bool type.

Forgot to say I am using `set -euo pipefail`. Azure DevOps has strange scripts error handling, but before update it worked. Dunno why it decide to fail on println :D

Anyway I'll try to set the flag and see if it works. Many thanks for swift reply

**Comment by sbugalski** [comment]
One more thing. I still can't figure out why it sometimes prints the message and sometimes not

Different clusters but same script is executed...
![image](https://user-images.githubusercontent.com/45152735/148770217-01cc376e-75a3-438c-87f0-e0ab8bb62904.png)
![image](https://user-images.githubusercontent.com/45152735/148770249-a8acbdc6-c97a-4c58-8aa9-1af9015181ef.png)

**Comment by mumoshu** [comment]
@sbugalski helm-diff always print that message when you ommit `--three-way-merge` flag, which implies that Azure DevOps pipeline sometimes ignores the output to stderr and sometimes not.

**Comment by sbugalski** [comment]
Many thanks once again. Using flag helped me a lot :)

**Comment by mumoshu** [comment]
@sbugalski Thanks for confirming! Probably I'll follow up with making logs a bit less verbose, by letting it emit only when the feature is actually enabled via the envvar. I'm not entirely sure how that affects your use-case but I hope it doesn't make thing worse.
