### ISSUE TITLE
Installation fails with busybox sh in $PATH

### ISSUE THREAD

**Issue by gdaszuta** [databus23/helm-diff#345]
So there is one funny behavior which was quite head-scratcher for me – trying to install helm-diff with one of my environments was giving me error:
```
No prebuild binary for Linlx-amd64.
```
For some reason I had busybox shell in my $PATH, so installer script was using this, and then `tr [:upper:] [:lower:]` was working in non-GNU way substituting `Linux` with `Linlx` instead of `linux`.

By the way, original script on https://github.com/technosophos/helm-template/blob/master/install-binary.sh wouldn't fail in the same way, because it is specifically calling `/usr/bin/env bash` instead of `/usr/bin/env sh`.

**Comment by mumoshu** [comment]
@gdaszuta Thanks! First of all thanks for pointing it out that it doesn't fail with the original install-binary script.

But we won't just revert back to bash as we moved to sh for extra compatibility.
Probably the only way forward would be to somehow fix our script to handle busybox case.
If you have some experience writing a good sell script, I'd appreciate it if you could contribute the fix. Thanks!

**Comment by gdaszuta** [comment]
@mumoshu since the script is already using `awk`, I would suggest replacing `tr '[:upper:]' '[:lower:]'` with `awk '{print tolower($0)}'` – this will work with both GNU awk and busybox awk:
```
$ uname | /usr/bin/awk '{print tolower($0)}'
linux
$ uname | /usr/bin/busybox awk '{print tolower($0)}'
linux
```

**Comment by mumoshu** [comment]
We've added Alpine Linux(which is based on BusyBox) to our test matrix in #360. It's passing so probably we've already fixed this in somewhere?
Closing as resolved, but please feel free to reopen, or create another issue for adding BusyBox to the test matrix so that we won't break it in the future!
Thanks.
