### ISSUE TITLE
ci: Add more Linux distros to the test matrix of install-binary.sh

### ISSUE THREAD

**Issue by mumoshu** [databus23/helm-diff#347]
I recently saw it can easily break on untested distros due to various shell script portability issues.
Thanks to #335 by @jkroepke we now have tests for cygwin, windows, and ubuntu.

GitHub Actions doesn't provide busybox or alpine VMs (it shouldn't 😃 ) so the remaining task would be to add containerized tests for install-binary.sh on those two distros, so that the coverage is complete.

**Comment by mumoshu** [comment]
Linking #345, #322, #317

**Comment by jkroepke** [comment]
Take a look at https://github.com/jkroepke/helm-secrets/blob/3cfb7651735a6d7e116ecb70ec6331e14fa38849/.github/workflows/ci.yaml#L43 how I run the test inside containers.

**Comment by mumoshu** [comment]
@jkroepke Thanks for the info and fixing it for cygwin at #353!

**Comment by mumoshu** [comment]
I believe this can be closed once someone adds a build for alpine
