### ISSUE TITLE
Ignore diff created by helm when using --three-way-merge

### ISSUE THREAD

**Issue by yuvalhnoga** [databus23/helm-diff#349]
Hi,
Currently when using the `--three-way-merge` options it shows some changes that were made by helm and it would be nice if it didn't show them because they are irrelevant. 

Example:
```diff
  apiVersion: apps/v1
  kind: Deployment
  metadata:
-   annotations:
-     deployment.kubernetes.io/revision: "5"
    creationTimestamp: "2021-04-08T14:16:14Z"
-   generation: 8
+   generation: 9
```

**Comment by mumoshu** [comment]
@yuvalhnoga Hey. `deployment.kubernetes.io/revision: "5"` does look irrelevant because it's added automatically by K8s. I want your insight about `generation`- what's the rationale of marking `generation` irrelevant, you think?

**Comment by mumoshu** [comment]
@yuvalhnoga I see. Thanks for validation 😄

**Comment by mumoshu** [comment]
We already have similar cleanup logics in https://github.com/databus23/helm-diff/blob/9086688c97f0a0aeba5be186b31be588d7f44ae0/cmd/upgrade.go#L546-L572

Could anyone contribute?
