### ISSUE TITLE
TLS secured Tiller doesn't work

### ISSUE THREAD

**Issue by tboerger** [databus23/helm-diff#35]
Hi,

my Helm installation is done with TLS, since the diff sub command doesn't provide any `--tls` flag I'm not able to use this tool with my setup :(

**Comment by sprutner** [comment]
+1, I would love to see support for this.

**Comment by maver1ck** [comment]
@mumoshu 
Any new release with that ?

**Comment by mumoshu** [comment]
@maver1ck Just released v2.9.0+3!
