### ISSUE TITLE
--three-way-merge don't find Auth Provider with gcp

### ISSUE THREAD

**Issue by frank-berlin** [databus23/helm-diff#354]
When I use --three-way-merge option I get the error:
```
Error: Kubernetes cluster unreachable: no Auth Provider found for name "gcp"
Error: plugin "diff" exited with error
```
used cmd line is:
```
helm --kube-context test diff upgrade echo ../std-app --three-way-merge
```

Same it I don't use  `--kube-context`

without three-way-merge it works.

used helm:
version.BuildInfo{Version:"v3.7.2", GitCommit:"663a896f4a815053445eec4153677ddc24a0a361", GitTreeState:"clean", GoVersion:"go1.16.10"}
plugin:
diff      	3.3.2  	Preview helm upgrade changes as a diff

**Comment by mumoshu** [comment]
Ah, I thought it had to import certain packages from `client-cmd` to make various auth providers work.

**Comment by mumoshu** [comment]
@frank-berlin #355 should fix it.

Would you mind building testing your own `helm-diff` from #355 by running `go build .` with go 1.17.x on the cloned repo? The command will produce `./helm-diff` which can be run directly like `HELM_NAMESPACE=default ./helm-diff upgrade ...`.

**Comment by frank-berlin** [comment]
it works now, thank you
As I see your build are failing
