### ISSUE TITLE
env var for --no-hooks flag

### ISSUE THREAD

**Issue by carlosrmendes** [databus23/helm-diff#361]

**Comment by mumoshu** [comment]
I don't think this makes sense, as your wrapper script/command should usually support this as a command-line flag or a configuration key, instead of an envvar that is implicitly passed down to helm-diff.

**Comment by carlosrmendes** [comment]
I'm trying to use with helmfile command. If I set the HELM_DIFF_USE_UPGRADE_DRY_RUN=true, it resolves the differences regarding the apiVersions diffs but shows me the removal of all helm hooks resources, with a huge output because I have a lot of them.
