### ISSUE TITLE
With --three-way-merge resource shown as deleted

### ISSUE THREAD

**Issue by MarvinCai** [databus23/helm-diff#362]
I'm playing with the new --three-way-merge (this is great feature)
But I'm seeing some weird result with --three-way-merge
The scenario is 
1. Create a release with chart A, 
2. Move some resources out of chart A to create chart B, 
3. Create a empty release of chart B(no resources)
4. Patch annotation of existing resource then upgrade release of chart B so it can somehow "take over" the existing resource.

That should be possible if resources have the same namespaced name.
I'm using helm diff with --three-way-merge to verify the result, but somehow my statefulset is marked as deleted in diff output, while in output some other resources(svc, pdb, sa) is properly updated. All resources generated by chart B have name/namespace matching existing resource. So I'm wondering is this an expected behavior since statefulset only allow updating specific fields(e.g. 'replicas', 'template', and 'updateStrategy') or I misunderstand how 3 way merge works?

**Comment by MarvinCai** [comment]
I actually tried to run helm upgrade and seems chart B was able to take over ownership of the statefulset(when uninstalling chart B that sts was also deleted), but just the output of helm diff is bit confusing.

**Comment by MarvinCai** [comment]
So it's actually the statefulset, after limiting change to only  'replicas', 'template', and 'updateStrategy' fields, 
helm diff --three-way-merge can properly show the changed field instead of showing whole sts as deleted.

**Comment by mumoshu** [comment]
Apparently, this was related to #352.

> after limiting change to only 'replicas', 'template', and 'updateStrategy' fields,
helm diff --three-way-merge can properly show the changed fields instead of showing whole sts as deleted

Good to know! Thank you for sharing @MarvinCai
