### ISSUE TITLE
How to validate if K8s secrets are base64 encoded during helm diff? 

### ISSUE THREAD

**Issue by jaythamke** [databus23/helm-diff#366]
In the K8s secret manifest I put the secret at `data` field as non-base64 encoded secret. The `helm diff` execution works great and returns exit code `2` for diff.

However for `helm upgrade` it failed exit code `1` because the secret `data` is non-base64 encoded. 

I would like to know if there is a way to verify at `helm diff` stage that the secret is non-base64 encoded and return with `1`. Or is there any plan to implement this check? 

Thanks
Jayesh

**Comment by jaythamke** [comment]
Thanks for reply @mumoshu ,
I set `HELM_DIFF_THREE_WAY_MERGE=true` and executed `helm diff ....` but it does not catch when the secret is non base64 encoded.

**Comment by mumoshu** [comment]
Thanks! Then helm-diff seems to be not the right place to do such validations. Maybe a better approach would be to use `--post-renderer` in combination with a custom script/command that is designed to fail when the input k8s manifests had non-base 64 encoded secret values?

**Comment by lucasfcnunes** [comment]
+1
