### ISSUE TITLE
Helm diff upgrade on non-Helm resources

### ISSUE THREAD

**Issue by gw0** [databus23/helm-diff#367]
I have a couple of Helm charts deployed as a rendered manifest via ArgoCD (i.e. without `app.kubernetes.io/managed-by=Helm`). I thought I could use the `helm-diff` plugin to check for differences between a local version of the chart and the live resources.

Unfortunately, it fails due to a sanity check that does not make sense during a `diff` action:

```bash
$ helm diff upgrade foo . --allow-unreleased --reset-values
reading three way merge from env
********************

	Release was not present in Helm.  Diff will show entire contents as new.

********************
Error: Failed to render chart: exit status 1: Error: rendered manifests contain a resource that already exists. Unable to continue with install: ConfigMap "foo" in namespace "default" exists and cannot be imported into the current release: invalid ownership metadata; label validation error: missing key "app.kubernetes.io/managed-by": must be set to "Helm"; annotation validation error: missing key "meta.helm.sh/release-name": must be set to "foo"; annotation validation error: missing key "meta.helm.sh/release-namespace": must be set to "default"

Error: plugin "diff" exited with error
```

There is no `--force` option to turn off all sanity checks and just fetch all the resources and run a diff on them. Setting `HELM_DIFF_THREE_WAY_MERGE=false` also does not help.

A workaround is to add these annotations to the live resources before each `helm diff` (but they get immediately reverted if ArgoCD self-healing is turned on):
```bash
$ kubectl annotate $KIND $NAME meta.helm.sh/release-name=$RELEASE
$ kubectl annotate $KIND $NAME meta.helm.sh/release-namespace=$NAMESPACE
$ kubectl label $KIND $NAME app.kubernetes.io/managed-by=Helm 
```

**Comment by xiaomudk** [comment]
I also encountered this problem, my case is Argo CD + helmfile. I expect to use `helmfile diff` to see the changes directly when writing a chart locally, but the helm chart deployed by Argo CD has no annotations, so I can't use `helmfile diff`

**Comment by xiaomudk** [comment]
@databus23 @mumoshu Can you help me?

**Comment by kfirfer** [comment]
having the same issue: https://github.com/databus23/helm-diff/issues/404

**Comment by mumoshu** [comment]
@gw0 Thanks for clarifying! Have you already tried `argocd app diff --local`? I thought that's the command supposed to be used when you want to take diff against the live resources? I thought it was designed to work with whatever ArgoCD pugin.

**Comment by gw0** [comment]
> Have you already tried `argocd app diff --local`?

You are right, this should work if you have the Helm chart locally accessible (`helm pull ...`) and pass in the right Helm values. Thanks for the suggestion.
