### ISSUE TITLE
Make helm diff not fail when diffing a release that failed  

### ISSUE THREAD

**Issue by foklepoint** [databus23/helm-diff#37]
Currently helm-diff will complain with the following error if I try to diff a release that failed to deploy. 
```
Error: "kubernetes-dashboard" has no deployed releases
```

**Comment by foklepoint** [comment]
I'm unsure what the desired behavior in a case like this would be. We at reddit would at the very least want helm diff to not return a non-zero exit code, but up for discussion on what helm-diff should do in a case like this. i.e treat the release as not release and continue or just complain that the previous release failed and that we can't diff it

**Comment by foklepoint** [comment]
Also for clarity, helm allows you to upgrade failed releases, so failing in a case where the upstream release has failed might not be desirable for us in a CI environment where a CI run can totally fix the helm release failure but helm-diff exiting with a non-zero status code won't allow CI to continue onto that step

**Comment by mr-joshua** [comment]
link to failed job:  https://drone.dev.dev-cglcloud.com/API-Platform-Apps/bsapi-casc-account-cts/17/6

**Comment by foklepoint** [comment]
Sorry one minor clarification. With helm you need to pass the --force flag if you want to upgrade a failed release. Something similar with helm-diff would also be fine

**Comment by atombender** [comment]
Seconding this. It must be possible to diff against a failed deploy, since a failed deploy _is_ a deploy.

**Comment by foklepoint** [comment]
This can now be closed. This commit fixed the issue: https://github.com/databus23/helm-diff/commit/0cafd7c8174296cedd107e30a3b91a221083bfe8
