### ISSUE TITLE
Show only critical changes for `helm-diff`

### ISSUE THREAD

**Issue by hydeenoble** [databus23/helm-diff#371]
For us, the `helm-diff` tool is used within our CICD pipeline, It would be nice to have a flag that only shows critical differences. For example, resources that would be recreated.

**Comment by mumoshu** [comment]
Hey. How would you generalize the concept of "critical"?
Can it be implemented via multiple flags so that you can combine these flags for your own usecase?

**Comment by hydeenoble** [comment]
Thanks for your response @R-omk
