### ISSUE TITLE
Helm diff fails when --set variables start with a capital letter

### ISSUE THREAD

**Issue by ctr26** [databus23/helm-diff#374]
Input:

`helm diff  --suppress-secrets upgrade jupyterhub jupyterhub/jupyterhub --version 1.2.0 --namespace jupyterhub -f .helmsman-tmp/tmp748608288/327616155config.yaml  --set hub.config.GitHubOAuthenticator.oauth_callback_url="test" `

Error:

`interface conversion: interface {} is []interface {}, not map[string]interface {}`

Input and lower-case the G:

`helm diff  --suppress-secrets upgrade jupyterhub jupyterhub/jupyterhub --version 1.2.0 --namespace jupyterhub -f .helmsman-tmp/tmp748608288/327616155config.yaml  --set hub.config.gitHubOAuthenticator.oauth_callback_url="test" `

Runs successfully

I'm on the latest helm and helm-diff versions

**Comment by mumoshu** [comment]
@ctr26 Hey. I believe helm-diff just passes `--set` flags to `helm template` so I don't think there's any fault on helm-diff here.
Isn't it a bug in jupyterhub chart?
Would you mind confirming if that reproduces with other charts?

**Comment by ctr26** [comment]
It's bad practise by jupyterhub to sentence-case v camelcase for sure. I'll mention the bug in the main helm repo. Thanks
