### ISSUE TITLE
helm-diff doesn't recognize if deployment is changed manually

### ISSUE THREAD

**Issue by dinoba** [databus23/helm-diff#375]
I am using helm diff as part of gitops operator (to check if config and deployment match). helm diff runs each minute, pulls config and check for diff (I just parse helm diff --output simple response). 
I just found that if I change deployment manually (for example docker image tag) helm diff will not see difference.

Is there something I can use to force check?

I tried HELM_DIFF_THREE_WAY_MERGE=true helm diff upgrade --install -f ...
And this seems to work? Any better workaround?

**With** HELM_DIFF_THREE_WAY_MERGE
```
HELM_DIFF_THREE_WAY_MERGE=true helm diff upgrade --output simple --install ...   

Enabled three way merge via the envvar
xyz, video-client, Deployment (apps) to be changed.
Plan: 0 to add, 1 to change, 0 to destroy.
```

**Without** HELM_DIFF_THREE_WAY_MERGE
```
helm diff upgrade --output simple --install....     

Plan: 0 to add, 0 to change, 0 to destroy.
```

**Comment by mumoshu** [comment]
@dinoba Hey. Would you mind giving me a reproduction step? Which field you're missing from the diff output? When I last tried it, it did detect my manual changes. So I suspect this is specific to some API fields.

FWIW, there's code helm-diff runs to remove certain fields from the output that it thinks unnecessary
https://github.com/databus23/helm-diff/blob/1e87d3b7760b2237d5995d63a5f5ec566d907035/cmd/upgrade.go#L546-L574

**Comment by dinoba** [comment]
- deployment done via helm
- docker tag manually changed from develop-c2a844f to develop (by editin deployment)

if I run helm diff without HELM_DIFF_THREE_WAY_MERGE
```
$ helm diff upgrade --output simple --install -f lab.yaml -f ../config/helm-values.yaml deployment-xyz ./video/charts/client -n namespacexyz
Plan: 0 to add, 0 to change, 0 to destroy.

```

then I run with  HELM_DIFF_THREE_WAY_MERGE

```
$ HELM_DIFF_THREE_WAY_MERGE=true helm diff upgrade --install -f lab.yaml -f ../config/helm-values.yaml deployment-xyz ./video/charts/client -n namespacexyz
Enabled three way merge via the envvar
namespacexyz, deployment-xyz, Deployment (apps) has changed:
  apiVersion: apps/v1
  kind: Deployment
....
        containers:
-       - image: docker.io/company/deployment-xyz:develop
+       - image: docker.io/company/deployment-xyz:develop-c2a844f
...
```

**Comment by mumoshu** [comment]
@dinoba Thanks. Everything seems to be working as expected. Perhaps I misread your explanation on the issue first?

Anyway, to let it detect manual changes, you need to set `HELM_DIFF_THREE_WAY_MERGE`. Without that helm-diff doesn't do a three-way merge which is crucial to detect manual changes.

**Comment by dinoba** [comment]
OK, thanks. 

I didn't understand  this from docs
