### ISSUE TITLE
context deadline exceeded using latest helm-diff

### ISSUE THREAD

**Issue by clux** [databus23/helm-diff#38]
Hey,

Noticed that after the latest upgrade of helm diff last night, we started seeing consistent errors when issuing helm diff against anything.

```
07:31:24 Error: context deadline exceeded
07:31:24 Usage:
07:31:24   diff [flags] [RELEASE] [CHART]
07:31:24 
07:31:24 Flags:
07:31:24       --no-color               remove colors from the output
07:31:24       --reset-values           reset the values to the ones built into the chart and merge in any new values
07:31:24       --reuse-values           reuse the last release's values and merge in any new values
07:31:24       --set stringArray        set values on the command line (can specify multiple or separate values with commas: key1=val1,key2=val2)
07:31:24       --suppress stringArray   allows suppression of the values listed in the diff output
07:31:24   -q, --suppress-secrets       suppress secrets in the output
07:31:24   -f, --values valueFiles      specify values in a YAML file (can specify multiple) (default [])
07:31:24   -v, --version                show version
07:31:24 
07:31:24 Error: plugin "diff" exited with error
07:31:24 
```

It's likely related to https://github.com/kubernetes/helm/pull/3715 or https://github.com/kubernetes/helm/issues/2409 because `helm get manifest {svc}` seems to currently fail on our cluster anyway (hoping helm 2.9 will fix that), but the latest version of helm diff exposes this it seems.

We have confirmed that the latest change is the offending one because:

```sh
helm plugin install https://github.com/databus23/helm-diff --version 885e7a720dd31fa24ec50fd1681a86f2a7236c58
```

fixes our CI image again. We used to just get latest on each image build.

(Thanks a lot for this plugin by the way, has really helped the transparency of our kube CI system.)

**Comment by databus23** [comment]
Aargh, thanks for the feedback. Seems like `helm diff` is completely broken. Maybe I should back port that three line fix to make the latest version work again...

**Comment by databus23** [comment]
Can you confirm if the latest release (`v2.8.2+2`) fixes this issue?
