### ISSUE TITLE
Error when trying to use dapr chart

### ISSUE THREAD

**Issue by mortenbock** [databus23/helm-diff#380]
I have the following file:

    repositories:
      - name: dapr
        url: https://dapr.github.io/helm-charts/
    releases:
      - chart: dapr/dapr
        cleanupOnFail: false
        name: dapr
        namespace: dapr-system
        version: 1.6.0

When I run `helmfile diff` I get the following error:

    Error: unable to build kubernetes objects from release manifest: unable to recognize "": no matches for kind "Configuration" in version "dapr.io/v1alpha1"

It seems to refer to this file in the chart: https://github.com/dapr/dapr/blob/master/charts/dapr/charts/dapr_config/templates/dapr_default_config.yaml

If I install the chart using helm directly, there is no issue.

helmfile version v0.143.0
helm version: version.BuildInfo{Version:"v3.8.0", GitCommit:"d14138609b01886f544b2025f5000351c9eb092e", GitTreeState:"clean", GoVersion:"go1.17.5"}
helm-diff version: 3.4.2

Is this a bug in helm-diff?

**Comment by mumoshu** [comment]
@mortenbock Hey! Please check https://github.com/databus23/helm-diff/issues/189.
