### ISSUE TITLE
Enhancement: Add flag to allow ignoring of secrets

### ISSUE THREAD

**Issue by anton264** [databus23/helm-diff#384]
It would be nice to be able to do a diff and ignore assets which the user does not have access to.
Currently if the user in the kubeconfig does not have read access to secrets the diff will fail with message 
"Error: query: failed to query with labels: secrets is forbidden:"

If I as a user know that secrets are not important for my comparison then there should be a flag to tell helm diff to ignore secrets.

**Comment by mumoshu** [comment]
Hey. I'm a bit confused but how can you diff it if you have no access to secrets? As far as I know the default helm storage backend is K8s secrets which means the live helm release is stored as a helm release. If you can't fetch it you have nothing to take diff against.

**Comment by anton264** [comment]
I guess that shows my limited knowledge of helm. You are correct that it stores the release in a secret. Perhaps I have to implement a more fine grain control over which secrets can be viewed. 
If the user can only view helm release secrets but no other secrets, would that work or does helm diff look for all secrets in the namespace?

**Comment by mumoshu** [comment]
That would work. AFAIK each helm release secret is named after the release name. Try installing any helm releases and run and compare results of `kubectl get secret` vs `helm list`.

**Comment by anton264** [comment]
Thank you! Sorry for not researching more before posting.
