### ISSUE TITLE
Add "--normalize-manifests" flag as environment variable

### ISSUE THREAD

**Issue by Anthon129** [databus23/helm-diff#388]
Hi

I have a scenario using `helmfile apply` where the golang code behind the scenes runs  `helm diff upgrade` followed by `helm upgrade --install`. I need to add the flag `--normalize-manifests` (to helm diff command) due to other reasons but this flag is unknown to `helm upgrade` (causing it to fail) and I am not able to apply separate individual flags to each of the commands. The flags applied to  `helm diff upgrade` will be applied to `helm upgrade`. 

Can we add an environment variable (i.e. `HELM_DIFF_NORMALIZE_MANIFESTS=true`) that would have the same effect as `--normalize-manifests` ?

Thanks

**Comment by Anthon129** [comment]
Moved to issue [#388](https://github.com/databus23/helm-diff/issues/388)

**Comment by frank-berlin** [comment]
+1

**Comment by Anthon129** [comment]
was fixed in PR https://github.com/databus23/helm-diff/pull/389
