### ISSUE TITLE
Secret: kubectl.kubernetes.io/last-applied-configuration not redacted

### ISSUE THREAD

**Issue by antoinedeschenes** [databus23/helm-diff#390]
Hi, I have a case where a manually modified secret contains a `kubectl.kubernetes.io/last-applied-configuration` label with three-way-merge, containing the whole JSON of the previous secret version. The label is unfortunately printed out unredacted through helm diff. Maybe the plugin should handle this.

**Comment by antoinedeschenes** [comment]
Still relevant, there should be a way to suppress some labels from output.

**Comment by yxxhero** [comment]
please use this feature: https://github.com/databus23/helm-diff/pull/475
