### ISSUE TITLE
Chart/version label noise on each chart upgrade

### ISSUE THREAD

**Issue by danopia** [databus23/helm-diff#392]
I've been using helm-diff via helmfile for some time now to post a diff into a Github PR comment.
I'd like to do something about the nuisance label change that shows up for every single resource when a chart version changes.
I don't mind these labels changing on upgrade, and I feel other helm users view these same labels as noise too.

I didn't see any open discussions around reducing diff noise. I hope opening a new issue is acceptable. This is a pretty straightforward usecase at least.

For example, updating `jetstack/cert-manager` from `1.8.0` to `1.8.1`. The only actual change is the image tag in the deployments. But the printed diff is huge and quickly exceeds Github's max comment size, basically repeating this section for **all 48 resources**:

`$ helmfile [...] diff --context 5`

```diff
[...]
cert-manager, cert-manager-cainjector, ClusterRole (rbac.authorization.k8s.io) has changed:
...
    labels:
      app: cainjector
      app.kubernetes.io/name: cainjector
      app.kubernetes.io/instance: cert-manager
      app.kubernetes.io/component: "cainjector"
-     app.kubernetes.io/version: "v1.8.0"
+     app.kubernetes.io/version: "v1.8.1"
      app.kubernetes.io/managed-by: Helm
-     helm.sh/chart: cert-manager-v1.8.0
+     helm.sh/chart: cert-manager-v1.8.1
  rules:
    - apiGroups: ["cert-manager.io"]
      resources: ["certificates"]
      verbs: ["get", "list", "watch"]
    - apiGroups: [""]
...
cert-manager, cert-manager-cainjector, ClusterRoleBinding (rbac.authorization.k8s.io) has changed:
...
    labels:
      app: cainjector
      app.kubernetes.io/name: cainjector
      app.kubernetes.io/instance: cert-manager
      app.kubernetes.io/component: "cainjector"
-     app.kubernetes.io/version: "v1.8.0"
+     app.kubernetes.io/version: "v1.8.1"
      app.kubernetes.io/managed-by: Helm
-     helm.sh/chart: cert-manager-v1.8.0
+     helm.sh/chart: cert-manager-v1.8.1
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: cert-manager-cainjector
  subjects:
[...]
```

Potentially related:

* #371
* #365

**Comment by z0rc** [comment]
There is still interest in this.

**Comment by z0rc** [comment]
Not stale.

**Comment by LatVAlY** [comment]
Not stale.

**Comment by tolleiv** [comment]
This would be very valuable

**Comment by yxxhero** [comment]
hi. all. I will try to optimize code. what do you think of the value of the feature? @danopia @tolleiv @z0rc @LatVAlY @Sajfer

**Comment by LatVAlY** [comment]
I think as already explained above, reducing the noise on the diff, plus having a checksum by modifying a value the whole checksum would be showed as changed, which is logical but the diff would look so huge, I would say improving this without having to compromise the code quality.💭 as a thought :) 
Again thank you so much for the efforts!

**Comment by yxxhero** [comment]
@LatVAlY thanks for your advice. I will add features on top of the code quality prompts.

**Comment by z0rc** [comment]
For my case https://github.com/databus23/helm-diff/pull/475 was sufficient.

**Comment by tolleiv** [comment]
Comming late for this one, to add some value - `--suppress-output-line-regex "(app.kubernetes.io/version|chart):.*"` got rid of all the noise so far. Thanks!
