### ISSUE TITLE
plugin.yaml for 3.6.0 wasn't updated

### ISSUE THREAD

**Issue by fraenkel** [databus23/helm-diff#408]
When you do `helm plugin update diff` you end up with the 3.6.0 binary but `helm plugin list` will say 3.5.0.

```
$ /helm/plugins/helm-diff/bin/diff version
3.6.0
$ helm plugin list
NAME   	VERSION  	DESCRIPTION
diff   	3.5.0    	Preview helm upgrade changes as a diff
```

**Comment by databus23** [comment]
sorry I forget to push master when creating the release, should be fixed now
