### ISSUE TITLE
First existing manifest gets dropped

### ISSUE THREAD

**Issue by cwrau** [databus23/helm-diff#409]
When using flux, the manifests don't contain a leading `---`.

Therefore https://github.com/databus23/helm-diff/blob/master/manifest/parse.go#L97-L98 leads to the first manifest being dropped.

I would propose to just delete these lines as https://github.com/databus23/helm-diff/blob/master/manifest/parse.go#L104-106 already filters out empty YAML documents

**Comment by rfrebyLF** [comment]
Hello @cwrau, we ran into the same problem today from our side. We're not able to do a complet diff because there is one resource missing. Did you find a way to get around it ?
Are the leading hyphens set by helm and forgot by flux ? In this case, we should open an issue on flux.
