### ISSUE TITLE
Use new helm support for lookups in helm dry-run

### ISSUE THREAD

**Issue by MichaelMorrisEst** [databus23/helm-diff#449]
[PR 9426](https://github.com/helm/helm/pull/9426) in helm will allow setting the value for the --dry-run flag to enable the execution of lookups towards the cluster.
I would like to submit a PR that will use this new option in order to solve https://github.com/databus23/helm-diff/issues/263

I am hopeful the PR in helm will be merged soon and would like to start working on the implementation in helm-diff and would appreciate any thoughts. In particular, is it ok to change the implementation to always use "--dry-run=server" (i.e. execute lookups) or do we need the existing behaviour by default and a new flag in helm-diff to enable using the new helm flag?

**Comment by MichaelMorrisEst** [comment]
@databus23 any thoughts on how you would like to see this implemented?
i.e. is it ok to change the implementation to always use "--dry-run=server" (i.e. execute lookups) or do we need the existing behaviour by default and a new flag in helm-diff to enable using the new helm flag?

**Comment by databus23** [comment]
If the outcome as identical to the current output with the benefit that the `lookup` function is evaluated as it will be during upgrade I'm all for always using `--dry-run=server`. But we need to maintain backward compatibility with older helm versions that don't support the new flag yet and fallback to the currently used command invocation.

**Comment by dudicoco** [comment]
I'm all for the new flag as I've been waiting for it as well, however it should be added explicitly by the user due to the fact that this will make helm contact the k8s api server, which could be security concern for some users, especially when using a third party chart.

**Comment by mumoshu** [comment]
The support in helm-diff is available since 3.9.0 and considered complete since 3.9.4 released today! Enjoy!
