### ISSUE TITLE
Request to be a maintainer of helm-diff

### ISSUE THREAD

**Issue by yxxhero** [databus23/helm-diff#463]
I am an open-source enthusiast who has contributed extensively in the cloud-native field, including projects like Kubernetes (k8s), Helm, and Istio. Currently, I am a member of the Kubernetes community and a maintainer of Helm. I am also the maintainer of Helmfile. Given the close relationship between Helmfile and Helm-diff, I would like to join the maintenance efforts of Helm-diff as well, in order to foster the development of both projects.

@databus23 @mumoshu 

looking forward to your feedback. thanks so much.

**Comment by mumoshu** [comment]
@yxxhero To introduce yourself to the helm-diff community, I think, you should start by submitting pull requests / triaging issues first! helm-diff is an independent project, and not all helm-diff users are helmfile users.
WDYT? @databus23 

That said, I welcome you to the community and encourage you to become another maintainer! You'll be the superpower of the helm-diff project!! 😄

**Comment by yxxhero** [comment]
@mumoshu thanks so much. 👍

**Comment by databus23** [comment]
Good Morning.

I couldn't have put it better then @mumoshu. You are very welcome to join this project. Lets see were it take us.

**Comment by yxxhero** [comment]
@databus23 thanks so much. What I should do next? could you give me some permissions about helm-diff?

**Comment by databus23** [comment]
As @mumoshu said:

> To introduce yourself to the helm-diff community, I think, you should start by submitting pull requests / triaging issues first!

As with all open source projects it always starts with contributing either by submitting your own PRs or triaging/reviewing other peoples submissions.
No extra privileges are required to do so.
Becoming a maintainer with write access to the repository requires building that trust first.

**Comment by yxxhero** [comment]
@databus23 ok. got it.

**Comment by yxxhero** [comment]
@mumoshu @databus23 I had done a lot and hope to be recognized by joining helm-diff. Thanks so much.

**Comment by mumoshu** [comment]
Thanks and welcome to the team @yxxhero!
