### ISSUE TITLE
memcache.go error|warning displayed since 3.8.0 when using three-way-merge

### ISSUE THREAD

**Issue by tof1a** [databus23/helm-diff#470]
Since version 3.8.0 (is not present in 3.7.0), we can see plenty of error|warning messages like that one, when using three-way-merge option:
`E0608 14:20:59.724655   27649 memcache.go:255] couldn't get resource list for webhook.cert-manager.io/v1beta1: the server is currently unable to handle the request`

**Comment by yxxhero** [comment]
please ues latest version.
