### ISSUE TITLE
Support the new set-literal argument

### ISSUE THREAD

**Issue by plnordquist** [databus23/helm-diff#474]
Helm 3.12.0 seems to have introduced a set-literal argument to allow passing a literal value instead needing to escape strings with set or set-string.  The commit that introduced this feature is at https://github.com/helm/helm/commit/0833318 and the PR is at https://github.com/helm/helm/pull/9182.  The Helm Diff plugin should support this argument.

**Comment by interone-ms** [comment]
Relevant for my usecase as well, I'd be grateful if this could be implemented!

**Comment by interone-ms** [comment]
@plnordquist I had an attempt at this myself, if you're still interested you can fetch my fork's master branch and try it out. For me, it worked.
