### ISSUE TITLE
CI workflow doesn't test builded version

### ISSUE THREAD

**Issue by bonddim** [databus23/helm-diff#478]
Builded version is checked in `build` job only with this step:
https://github.com/databus23/helm-diff/blob/882b2110494e90c05cb0ada55ed2144efcc0e823/.github/workflows/ci.yaml#L38-L42

Installing from plugin directory in `helm-install` and `integration-tests` jobs invokes install hook, which downloads binary from latest release: 
https://github.com/databus23/helm-diff/blob/882b2110494e90c05cb0ada55ed2144efcc0e823/.github/workflows/ci.yaml#L93-L94
https://github.com/databus23/helm-diff/blob/882b2110494e90c05cb0ada55ed2144efcc0e823/.github/workflows/ci.yaml#L113-L114
Both these jobs are for testing `install-binary.sh` only and doesn't relate to binary itself.

It's better to move these tests to separate workflow like in #477 and write new jobs to test builded artifact on different OS-ARCH if needed.

**Comment by yxxhero** [comment]
done
