### ISSUE TITLE
circleci ci not working

### ISSUE THREAD

**Issue by yxxhero** [databus23/helm-diff#484]
please see: https://app.circleci.com/pipelines/github/databus23/helm-diff/383

**Comment by yxxhero** [comment]
@mumoshu

**Comment by mumoshu** [comment]
@yxxhero Good catch! Probably we can just let the circleci pipelines go?
Apparently we already do much more than the circleci pipeline in our GH actions workflows...

https://github.com/databus23/helm-diff/blob/master/.circleci/config.yml
vs
https://github.com/databus23/helm-diff/tree/master/.github/workflows
