### ISSUE TITLE
How to view only the diff between values not the manifest ?

### ISSUE THREAD

**Issue by fmiqbal** [databus23/helm-diff#486]
I want to view the diff on currently deployed user-values to the to-be-applied values, not the manifest, is it possible ?

**Comment by TimeBye** [comment]
this feature is really great

**Comment by juv** [comment]
I was looking for this as well. I sometimes have huge configMaps basically bloat the output of `helm diff upgrade ...` when only a few lines in between the rest of the content changes.

It would be great if there was an option to have a kind of minimal output, showing only the path of the file and the lines that have changes (currently highlighted in red / green in the console output).

**Comment by 880831ian** [comment]
@fmiqbal @TimeBye @juv 

Hello, for your problem, you can try to use --context number to solve it. You can set the number of lines before and after the difference is displayed. Suppose I want to display the upper and lower 5 lines of the difference. Just add --context 5.

--context int output NUM lines of context around changes (default -1)

![截圖 2024-04-24 上午11 24 01](https://github.com/databus23/helm-diff/assets/42373091/326ba8a1-8613-4c2e-82f8-0c08b0c1753f)
