### ISSUE TITLE
helm plugin install https://github.com/databus23/helm-diff install not the latest version

### ISSUE THREAD

**Issue by ingoziemann** [databus23/helm-diff#488]
Please make the people aware that helm plugin install https://github.com/databus23/helm-diff is not takeing the latest relase also helm plugin update is not updateing to the latest. In special with helmfile versions greater then 0.144 .0 it creates issues that the diff is failing due to the missing --color option.

**Comment by tehseenshahab** [comment]
You can use this command to install the master version. 
`helm plugin install https://github.com/databus23/helm-diff --version master`
