### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by jBouyoud** [databus23/helm-diff#497]
Hi,

Helm 1.13 is now "live".
Is it possible to get a new release of helm-diff to use --dry-run=server new field 

🙏  Many thanks

**Comment by cybrwshl** [comment]
what blocks a new release?

**Comment by jBouyoud** [comment]
@yxxhero @mumoshu When do you plan the next release? 

Thanks

**Comment by yxxhero** [comment]
@jBouyoud sorry. I have no permission. 
@mumoshu ping

**Comment by mumoshu** [comment]
Hey everyone! Sorry for the delayed response. I believe we have to work on #499 before cutting any new release!

**Comment by jBouyoud** [comment]
Hi sorry for the noise. Thanks for your answer. Let me known if I can help with #499 . See you
