### ISSUE TITLE
helm 3.10.0 helm diff --insecure-skip-tls-verify Error: unknown flag: --insecure-skip-tls-verify

### ISSUE THREAD

**Issue by HuLaLaGa** [databus23/helm-diff#503]

**Comment by HuLaLaGa** [comment]
Helm: 3.10.0
Helm-Diff: 3.8.1
command: helm diff --insecure-skip-tls-verify
error: Error: unknown flag: --insecure-skip-tls-verify

**Comment by tjanson** [comment]
I ran into this as well with Helm v3.13.1, helm-diff v3.8.1. Did this work with any previous version? (Then perhaps I could downgrade.)

**Comment by tjanson** [comment]
I guess this is a bug in #462 ?

**Comment by HuLaLaGa** [comment]
![image](https://github.com/databus23/helm-diff/assets/34408166/82e306d5-6ee6-4f85-a4e9-aa04b70d6069)

**Comment by HuLaLaGa** [comment]
![image](https://github.com/databus23/helm-diff/assets/34408166/70089cb5-c6ab-4d64-a982-c041161f7979)

**Comment by HuLaLaGa** [comment]
![image](https://github.com/databus23/helm-diff/assets/34408166/174b3509-cbb8-4eb2-9d88-711c8e89d19f)

**Comment by yxxhero** [comment]
@tjanson PR is welcome.

**Comment by yxxhero** [comment]
I can's reproduce this issue.

**Comment by yxxhero** [comment]
see: https://github.com/helm/helm/pull/12856
