### ISSUE TITLE
`--color` flag doesn't work anymore 

### ISSUE THREAD

**Issue by dvarrazzo** [databus23/helm-diff#536]
In v3.9.2. `--color` doesn't force a coloured output anymore.

- In 2.8.1 a command such as `helm diff upgrade NAME CHART --color | cat` would show a coloured result.
- In 2.9.2 the output is monochrome.

If the output is direct to TTY, 2.9.2 produces a coloured output as well. It's the `--color` flag to force it to seem broken.

**Comment by yxxhero** [comment]
@dvarrazzo PR is welcome

**Comment by yxxhero** [comment]
https://github.com/databus23/helm-diff/pull/499   this PR breaks some flag checks. maybe we can only support --dry-run="***", and remove --dry-run?  @mumoshu

**Comment by mumoshu** [comment]
@dvarrazzo Thanks for reporting! We're fixing that via #547.
