### ISSUE TITLE
Windows installation throws error when it tries to run post install hook

### ISSUE THREAD

**Issue by rgembalik** [databus23/helm-diff#55]
On windows, when I try to install the plugin it tries to run `.sh` file (I presume from `hooks.install`), which throws an error (since windows doesn't natively run `sh` files, nor there is an `install-binary.sh` in the release `tgz`). When I manually download the release and paste it into `.helm/plugins`, then it looks for `.helm\\plugins\\diff/bin/diff` which is incorrect since the `tgz` file contains `exe` in the main directory. 

It all runs well if I download `tgz` release, paste it manually, create `bin` folder for it, and throw `.exe` file in the `bin` folder.

**Comment by Tzrlk** [comment]
I get a different error during the post-install:
```
helm plugin install https://github.com/databus23/helm-diff
No prebuild binary for windows-386.
Failed to install helm-diff
\tFor support, go to https://github.com/databus23/helm-diff.
Error: plugin install hook for "diff" exited with error
```
(yes, the "\t" appears to have been escaped before printing)

Predictably followed by this when I go to run `helm diff help`:
```
helm diff help
Error: exec: "C:\\Users\\tzrlk\\.helm\\plugins\\helm-diff/bin/diff": file does not exist
```

**Comment by cilerler** [comment]
go away **stale** bot

**Comment by cilerler** [comment]
go away stale bot

**Comment by eshepelyuk** [comment]
The issue stil exists

```
C:\Users\Evgeny>helm plugin install https://github.com/databus23/helm-diff --version master
Windows Subsystem for Linux has no installed distributions.
Distributions can be installed by visiting the Microsoft Store:
https://aka.ms/wslstore
Error: plugin install hook for "diff" exited with error
```

**Comment by cilerler** [comment]
go away stale bot

**Comment by cilerler** [comment]
go away stale bot

**Comment by mumoshu** [comment]
Hey! Honestly I don't know how I can test this myself because I don't own a windows pc.

But anyway, @Tzrlk's issue and @rgembalik's second issue seems to be caused by this line https://github.com/databus23/helm-diff/blob/master/plugin.yaml#L8 as @rgembalik has described. If we changed it to `command: "$HELM_PLUGIN_DIR\bin\diff"` it would indeed work for Windows, but not on *nix.

I'm now wondering how helm itself is supposed to support plugins on Windows? 🤔

**Comment by mumoshu** [comment]
So the community direction seems like we should instruct users to use it on WSL.

https://github.com/helm/helm-2to3/pull/118

**Comment by mumoshu** [comment]
The upstream issue to add support for plugin installation on Windows is https://github.com/helm/helm/issues/7117

**Comment by Tzrlk** [comment]
Yeah, I love how helm seems to have completely different plugin storage
mechanisms for each OS.

**Comment by cilerler** [comment]
go away stale bot
