### ISSUE TITLE
specifying a version breaks in certain situations

### ISSUE THREAD

**Issue by sstarcher** [databus23/helm-diff#58]
```helm plugin install https://github.com/databus23/helm-diff                                                                         

Downloading https://github.com/databus23/helm-diff/releases/download/v2.9.0%2B2/helm-diff-macos.tgz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   609    0   609    0     0   2953      0 --:--:-- --:--:-- --:--:--  2956
100 4775k  100 4775k    0     0  2630k      0  0:00:01  0:00:01 --:--:-- 3116k
Preparing to install into /Users/sstarcher/.helm/plugins/helm-diff
cp: /tmp/helm-diff/diff/diff: No such file or directory
Failed to install helm-diff
\tFor support, go to https://github.com/databus23/helm-diff.
Error: plugin install hook for "diff" exited with error```

**Comment by sstarcher** [comment]
If I run the install-binary.sh directly from the ~/.helm/plugins/helm-diff it works

```
./install-binary.sh                                                                                                             
Downloading https://github.com/databus23/helm-diff/releases/download/v2.9.0%2B2/helm-diff-macos.tgz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   609    0   609    0     0   2675      0 --:--:-- --:--:-- --:--:--  2671
100 4775k  100 4775k    0     0  2830k      0  0:00:01  0:00:01 --:--:-- 6821k
Preparing to install into /Users/sstarcher/.helm/plugins/helm-diff
helm-diff installed into /Users/sstarcher/.helm/plugins/helm-diff/helm-diff

The Helm Diff Plugin
```

**Comment by databus23** [comment]
The plugin installation mechanism is driving my crazy. There are so many edge cases when it comes to working with the git repo cloned by helm.

Can you retry after clearing out: `~/.helm/cache/plugins/https-github.com-databus23-helm-diff/`

**Comment by sstarcher** [comment]
Yep, wiping out the cache worked for me.  I now can't reproduce the issue.

**Comment by sstarcher** [comment]
@databus23 I'm going to re-open this issue.  I also have a docker container that was previously installing `v2.9.0+1` and after switching to +2 it fails everytime.

`helm plugin install https://github.com/databus23/helm-diff` works fine
`helm plugin install https://github.com/databus23/helm-diff --version 2.9.0+2` fails to install with the same error that I had locally.

I forked the repo and made a change to add `set -x` to the script to try and debug why it's failing, but on my fork I can't reproduce the error.  I tried installing from the SHA and I deleted the `v2.9.0+2` tag on my repo and moved it to my debug addition and could still not produce the problem.

So far the only way to work around this in my docker container is to not specify the version of the plugin I want to install.

**Comment by majewsky** [comment]
I'm having the same problem on linux-amd64. The root cause appears to be that the tarball is not structured the way the install script expects. The following patch (applied to `$HELM_HOME/plugins/helm-diff`) causes `install-binary.sh` to work correctly for me (when installing 2.10.0+1): 

```diff
diff --git a/install-binary.sh b/install-binary.sh
index 20fca4c9d2..42846d596e 100755
--- a/install-binary.sh
+++ b/install-binary.sh
@@ -82,7 +82,7 @@ installFile() {
   HELM_TMP="/tmp/$PROJECT_NAME"
   mkdir -p "$HELM_TMP"
   tar xf "$PLUGIN_TMP_FILE" -C "$HELM_TMP"
-  HELM_TMP_BIN="$HELM_TMP/diff/diff"
+  HELM_TMP_BIN="$HELM_TMP/diff/bin/diff"
   echo "Preparing to install into ${HELM_PLUGIN_PATH}"
   cp "$HELM_TMP_BIN" "$HELM_PLUGIN_PATH"
 }
```
