### ISSUE TITLE
Upgrading to newer version does not deploy the binary

### ISSUE THREAD

**Issue by cmeury** [databus23/helm-diff#59]
### Steps

I upgraded from 2.8.0+1 to 2.9.0+2:

```
$ helm plugin list
NAME   	VERSION	DESCRIPTION
diff   	2.8.0+1	Preview helm upgrade changes as a diff
$ helm plugin update diff
Updated plugin: diff
$ helm plugin list
NAME   	VERSION	DESCRIPTION
diff   	2.9.0+2	Preview helm upgrade changes as a diff
```

### Observation

Now, the binary is not available anymore:

```
$ helm diff
Error: fork/exec /Users/ced/.helm/plugins/helm-diff/bin/diff: no such file or directory
```

### Remarks
Could an [`update` hook](https://github.com/kubernetes/helm/blob/master/pkg/plugin/hooks.go#L25) in `plugin.yaml` help here?

### Workaround

Reinstalling resolves the situation:

    $ helm plugin remove diff && helm plugin install https://github.com/databus23/helm-diff --version v2.9.0+2

**Comment by maver1ck** [comment]
I tried to add update hook.

https://github.com/maver1ck/helm-diff

Result:
```
maverick@CARBON:~$ helm plugin install https://github.com/maver1ck/helm-diff/
Downloading https://github.com/databus23/helm-diff/releases/download/v2.9.0%2B2/helm-diff-linux.tgz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   609    0   609    0     0    412      0 --:--:--  0:00:01 --:--:--   412
100 4776k  100 4776k    0     0   425k      0  0:00:11  0:00:11 --:--:--  653k
Preparing to install into /home/maverick/.helm/plugins/helm-diff
helm-diff installed into /home/maverick/.helm/plugins/helm-diff/helm-diff

***

maverick@CARBON:~$ helm plugin update diff --debug
[debug] loading installed plugins from /home/maverick/.helm/plugins
Error: Failed to update plugin diff, got error (plugin does not exist)

```

**Comment by maver1ck** [comment]
OK.
Found the reason of this problem.
PR is ready.

**Comment by cmeury** [comment]
@maver1ck Looks like it tries to `stat` the wrong path. In your strace snippet it says `/home/maverick/.helm/plugins/helm-diff.git` while the actual location seems to be  the folder `/home/maverick/.helm/plugins/helm-diff`. 

Looking at the relevant [code](https://github.com/kubernetes/helm/blob/master/pkg/plugin/installer/installer.go#L59) [sections](https://github.com/kubernetes/helm/blob/master/pkg/plugin/installer/base.go#L47), it seems that install does `path.Dir(i.Path())`, while update does `i.Path()`.

But I could not easily determine what goes wrong -- maybe it helps to look at the script used by a  different plugin (that is used in its plugin update hook): https://github.com/nouney/helm-gcs/blob/master/scripts/install.sh

**Comment by cmeury** [comment]
Ohh, good to hear :D I think when I opened the file in your branch you already fixed it so I never saw the erroneous "helm" :)

**Comment by maver1ck** [comment]
I was installing from github/maver1ck/helm-diff and should from helm-diff.git.
There is still bug in upgrade script ;)

**Comment by maver1ck** [comment]
PS. There is a mess in helm plugins. Sometimes .git extension is removed, sometimes not.
