### ISSUE TITLE
Oddity with chart searching

### ISSUE THREAD

**Issue by sstarcher** [databus23/helm-diff#60]
* Running `helm search private/elasticsearch` returns results
* Running `helm diff upgrade derp private/elasticsearch --allow-unreleased` fails with

```
Error: chart "elasticsearch" matching  not found in private index. (try 'helm repo update'). No chart version found for elasticsearch-
Usage:
  diff upgrade [flags] [RELEASE] [CHART]

Examples:
  helm diff upgrade my-release stable/postgresql --values values.yaml

Flags:
      --allow-unreleased       enables diffing of releases that are not yet deployed via Helm
  -h, --help                   help for upgrade
      --reset-values           reset the values to the ones built into the chart and merge in any new values
      --reuse-values           reuse the last release's values and merge in any new values
      --set stringArray        set values on the command line (can specify multiple or separate values with commas: key1=val1,key2=val2)
      --suppress stringArray   allows suppression of the values listed in the diff output
  -q, --suppress-secrets       suppress secrets in the output
  -f, --values valueFiles      specify values in a YAML file (can specify multiple) (default [])
      --version string         specify the exact chart version to use. If this is not specified, the latest version is used

Global Flags:
      --no-color   remove colors from the output

Error: plugin "diff" exited with error
```

**Comment by sstarcher** [comment]
It looks like the root cause of the issue is only having pre-released versions and no released version.  When helm-diff is searching it's searching only for released versions.  The default behavior of `helm search` is to show pre-released versions.

**Comment by mumoshu** [comment]
@sstarcher What if you added `--version ">0.0.0-a"` to `helm diff upgrade`?

The context is https://github.com/helm/helm/issues/2407 and https://github.com/technosophos/k8s-helm/commit/28ec92355bd676c5775ea82504cde5a3465000a0.

helm-diff seems to run an equivalent of `helm fetch`, so the fix should be brought by how we could make `helm fetch` to discover prereleased versions.
