### ISSUE TITLE
Helm diff should flatten ConfigMapList objects

### ISSUE THREAD

**Issue by madaraszg-tulip** [databus23/helm-diff#601]
This issue is similar to [https://github.com/databus23/helm-diff/issues/201](https://github.com/databus23/helm-diff/issues/201). 
There are multiple types of list objects, one of them is ConfigMapList which stores a number of ConfigMap entries. 
It would be great if helm diff expanded these too. 

The errors I'm getting are: 
`Error: Found duplicate key "namespace, , ConfigMapList (v1)" in manifest`

**Comment by yxxhero** [comment]
@madaraszg-tulip could you give me some example? So I can debug and fix it.

**Comment by madaraszg-tulip** [comment]
[helm-diff-test.zip](https://github.com/databus23/helm-diff/files/15150736/helm-diff-test.zip)

Install this chart, then change templates/configmaplist2.yaml and try helm diff

**Comment by yxxhero** [comment]
@mumoshu ping. WDYT?

**Comment by yxxhero** [comment]
@madaraszg-tulip fixed. thanks your advice. I match all list resource.

**Comment by yxxhero** [comment]
see: https://github.com/databus23/helm-diff/releases/tag/v3.9.6 released.
