### ISSUE TITLE
Don't output help on `helm plugin install`

### ISSUE THREAD

**Issue by z0rc** [databus23/helm-diff#605]
I'm installing helm-diff as part of CI pipeline. Every time plugin installation outputs help page.

I found this unwelcome, as in CI pipeline context this output is effectively a noise. Also it isn't possible to properly silence it. I can do `helm plugin install ... >/dev/null`, but this will also omit output from helm itself, which is actually valuable.

**Comment by yxxhero** [comment]
PR is welcome

**Comment by z0rc** [comment]
@yxxhero I can just remove https://github.com/databus23/helm-diff/blob/master/install-binary.sh#L146-L152 and https://github.com/databus23/helm-diff/blob/master/install-binary.sh#L166, right? Or do you expect something else?

**Comment by yxxhero** [comment]
@mumoshu @databus23  WDYT?

**Comment by yxxhero** [comment]
@z0rc PR is welcome.
