### ISSUE TITLE
Wrong package version for release v3.9.6

### ISSUE THREAD

**Issue by jbrt** [databus23/helm-diff#609]
Hello 👋 

It seems that the latest version v3.9.6 still contains the 3.9.5 value, the plugin.yaml hasn't been updated: 
https://github.com/databus23/helm-diff/blob/42881e87350087c51e156e4df603c326aae5dcba/plugin.yaml#L4

Can you please fix this 🙏 

Best regards

**Comment by yxxhero** [comment]
@jbrt oh. sorry. I forgot it. I will fix that as sone as I can.

**Comment by yxxhero** [comment]
fixed

**Comment by yxxhero** [comment]
@jbrt please take a try.
