### ISSUE TITLE
Helm installation error: Unable to update repository: exit status 1

### ISSUE THREAD

**Issue by fmunteanu** [databus23/helm-diff#611]
Hi @databus23,

When I try to install the plugin with `helm`, I get the following error:

```
$ helm version
version.BuildInfo{Version:"v3.14.2", GitCommit:"c309b6f0ff63856811846ce18f3bdc93d2b4d54b", GitTreeState:"clean", GoVersion:"go1.21.7"}

$ helm plugin install https://github.com/databus23/helm-diff --version=v3.9.6 --debug
[debug] vcs_installer.go:162: updating https://github.com/databus23/helm-diff
Error: Unable to update repository: exit status 1
helm.go:84: [debug] Unable to update repository: exit status 1
```

Could this be related to the latest changes performed 3 hours ago? Yesterday, everything was fine. Is there an action to be taken on my side, in order to address the issue?

**Comment by yxxhero** [comment]
I will see what happened.

**Comment by yxxhero** [comment]
@fmunteanu I can't reproduce your issue.

**Comment by fmunteanu** [comment]
@yxxhero I'm glad you did not find an issue. Can you please let me know how you tested the install? I would like to replicate the same steps. Myself, I login to a Kubernetes node where helm is installed and I run the command:

```
# curl -I https://github.com/databus23/helm-diff
HTTP/2 200
server: GitHub.com

# helm plugin install https://github.com/databus23/helm-diff --debug
[debug] vcs_installer.go:162: updating https://github.com/databus23/helm-diff
Error: Unable to update repository: exit status 1
helm.go:84: [debug] Unable to update repository: exit status 1
```

To give you more context, I was deploying my K3s cluster yesterday and everything was okay. Today, I performed a cluster reset and re-deployed the cluster, when I discovered the issue.

**Comment by yxxhero** [comment]
@fmunteanu please clean your helm cache. `$HOME/.cache/helm`

**Comment by fmunteanu** [comment]
@yxxhero thank you, that fixed the issue. The question is, what behaviour changed, since yesterday. I'm going to implement a task in Ansible to erase these related directories, while performing a reset.

```
- name: Remove generic files
  ansible.builtin.file:
    name: '{{ user_info.home }}/.{{ item }}'
    state: absent
  loop:
    - cache
    - config
    - local
```
