### ISSUE TITLE
Cannot build current master branch

### ISSUE THREAD

**Issue by cmeury** [databus23/helm-diff#64]
> ../../../k8s.io/helm/pkg/helm/client.go:515:13: resp.GetStatus undefined (type *grpc_health_v1.HealthCheckResponse has no field or method GetStatus)

Identified the first bad commit using git-bisect: e21ba6696afa63dd59b59f2a1678edcf4023ac02

**Comment by databus23** [comment]
works for me. Can you make the `vendor` dir is up to date: Remove it and run `glide install -v`

**Comment by cmeury** [comment]
Ah, thanks, works.  I'm new to go and glide especially. Sorry for the unnecessary issue.
