### ISSUE TITLE
linux tgz file does not contain install-binary.sh

### ISSUE THREAD

**Issue by helgi** [databus23/helm-diff#68]

**Comment by mumoshu** [comment]
@helgi Thanks for the report!

I'm trying to understand, why do you need install-binary.sh when you've installed helm-diff via the linux tgz? Perhaps to make `helm plugin upgrade` work?

**Comment by helgi** [comment]
At the time it was because of the GH rate-limiting (which I PRed a fix for part of the issue). My goal at the time was to embed the tgz in my docker image and run the install of a predefined version but without the install-binary.sh it was rather hard to even attempt that.
