### ISSUE TITLE
Can the diff to compare the struct of k8s resource ?

### ISSUE THREAD

**Issue by yan234280533** [databus23/helm-diff#7]
Can the diff to compare the struct of k8s resource ?

Can it do like this :
step1:  transfer the yaml to k8s resource
step2: compare the k8s resource struct

**Comment by databus23** [comment]
This helm plugin is only for previewing changes that helm would apply during an upgrade. Its not a generic diff tool for comparing local yaml files to in cluster resources.

**Comment by yan234280533** [comment]
For helm upgrade, the diff of  the struct which is builded from the yaml file, it is important too.

**Comment by databus23** [comment]
I'm not sure I understand what you are saying.

For this hypothetical invocation:

`helm diff RELEASE CHART --values some-values.yaml --set some.key=someval`

the plugin generates a diff between the manifests that are generated by

`helm upgrade RELEASE CHART --debug --dry-run --values  some-values.yaml --set some.key=someval` 

and

`helm get manifest RELEASE`.

So it compares the release that was deployed last by helm with what helm thinks it would apply given the local chart + values.

**Comment by yan234280533** [comment]
I am sorry, my Eglish is so poor. Which I want to say this that, in helm , the mainfest will build to resource.Info.  Can we have an compare of the resource.Infos which is build from the mainfest  yaml?

**Comment by databus23** [comment]
No worries. I'm still not sure what you mean by `resource.Info`?

**Comment by databus23** [comment]
Closing because no further feedback has been provided
