### ISSUE TITLE
Errors on CI related to helm diff

### ISSUE THREAD

**Issue by arielweinberger** [databus23/helm-diff#710]
Hi, we're using helmfile which uses helm diff. We've been using helmfile for many months but now we're receiving errors. I notice that there was a new release of helm-diff 7 minutes ago, so it could be related?

```
Downloading https://github.com/databus23/helm-diff/releases/download/v3.9.13/helm-diff-linux-amd64.tgz
curl: (22) The requested URL returned error: 404 
Failed to install helm-diff
	For support, go to https://github.com/databus23/helm-diff.
Error: plugin install hook for "diff" exited with error
/home/runner/work/_actions/mamezou-tech/setup-helmfile/v1.2.0/dist/index.js:1010
                error = new Error(`The process '${this.toolPath}' failed with exit code ${this.processExitCode}`);
                        ^

Error: The process '/home/runner/bin/helm' failed with exit code 1
    at ExecState._setResult (/home/runner/work/_actions/mamezou-tech/setup-helmfile/v1.2.0/dist/index.js:1010:25)
    at ExecState.CheckComplete (/home/runner/work/_actions/mamezou-tech/setup-helmfile/v1.2.0/dist/index.js:993:18)
    at ChildProcess.<anonymous> (/home/runner/work/_actions/mamezou-tech/setup-helmfile/v1.2.0/dist/index.js:887:27)
    at ChildProcess.emit (node:events:519:28)
    at maybeClose (node:internal/child_process:1105:16)
    at ChildProcess._handle.onexit (node:internal/child_process:305:5)
```

**Comment by yxxhero** [comment]
@arielweinberger retry. you should use fixed version helm-diff.

**Comment by yxxhero** [comment]
@arielweinberger I am releaseing the latest version.

**Comment by suhasdeshpande** [comment]
that fixed it! Thanks for quick response. Appreciate it. :)

**Comment by arielweinberger** [comment]
Thank you @yxxhero - it's used by the following action which apparently does not use a fixed version. I'll report to them.
https://github.com/helmfile/helmfile-action

Issue fixed as soon as the .tar.gz became available on the release. Thank you.

**Comment by yxxhero** [comment]
@arielweinberger please do as you say. I am the owner of the repo: https://github.com/helmfile/helmfile-action

**Comment by arielweinberger** [comment]
oops, just realized the issue was caused by a different action consuming `helm-diff` - it's this one: https://github.com/mamezou-tech/setup-helmfile

**Comment by yxxhero** [comment]
ok. got it.
