### ISSUE TITLE
Incompatible versions

### ISSUE THREAD

**Issue by bilus** [databus23/helm-diff#88]
1. I uninstalled and installed diff using:
```
helm plugin install https://github.com/databus23/helm-diff --version master
```
2. I have helm version 2.9.1 (client & server):

```
helm version
Client: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}
```

3. When I try to diff, I'm getting the following error:

```
Error: incompatible versions client[v2.10.0] server[v2.9.1]
incompatible versions client[v2.10.0] server[v2.9.1]
```

(I built 2.10 in the past and have it installed somewhere so maybe this has to do with the way you check it.)

**Comment by mumoshu** [comment]
@bilus Hey! The current master of helm-diff is built against helm/tiller 2.10.0, and unfortunately we don't cross-built as of today.

I don't even know how I could cross-build helm-diff against multiple versions of helm(perhaps swap vendored helm in a cross-build script thing?). Maybe I can took some time for cross-building if it's much in demand.

In the meantime, could you try v2.9.0+3, that is the latest release of helm-diff supports helm v2.9.x?

https://github.com/databus23/helm-diff/releases

**Comment by bilus** [comment]
I did the same, downgraded and it works. So the error is coming from library? Kinda odd if it does, I'd assume 2.10 is backwards compatible.
