### ISSUE TITLE
helm diff (--)version required tiller

### ISSUE THREAD

**Issue by jkroepke** [databus23/helm-diff#90]
Hi,

both commands

```
$ helm diff --version
Error: Unauthorized
$ helm diff version
Error: Unauthorized
```

required an active tiller. some commands like version or help should work without an active tiller.

**Comment by databus23** [comment]
That’s not possible unfortuanely. The plugin declares `useTunnel: true‘ which instructs Helm the setup a tunnel which happens before the plugin binary is even called.

**Comment by jkroepke** [comment]
So I have to open an issue at helm?

**Comment by jkroepke** [comment]
https://github.com/helm/helm/issues/4605

**Comment by jkroepke** [comment]
Small workaround:
`HELM_HOST=localhost helm diff -h`
