### ISSUE TITLE
Using helm-diff with a TLS secured tiller

### ISSUE THREAD

**Issue by proskehy** [databus23/helm-diff#93]
Is it not possible to use `helm-diff` with a tiller that requires cert authentication?

For normal `helm` commands I can use the appropriate flags: `helm list --tls --tiller-namespace ns`, but `helm diff revision my-release 2 --tls --tiller-namespace ns ` throws `Error: unknown flag: --tls`.

Am I just messing up the syntax or is this not supported?

**Comment by databus23** [comment]
I think this is fixed by #71

**Comment by proskehy** [comment]
You're right, I was using version v2.9.0+2. Thanks!
