### ISSUE TITLE
[bug] Helm diff shows resources as been removed

### ISSUE THREAD

**Issue by sfrique** [databus23/helm-diff#97]
Hello

I've been using this plugin for a while and it has worked fine for long!

But for some reason it isn't working when I try to diff after a big (json) change.
the way I am using this is kind o a hack but it's working. This is basically the hack:
```
$ cat grafana/templates/dashboards-json-configmap.yaml
{{ $root := .}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "grafana.fullname" . }}-dashboards-json
  labels:
    app: {{ template "grafana.name" . }}
    chart: {{ template "grafana.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
{{- if .Values.dashboards }}
  {{- range $key, $value := .Values.dashboards }}
    {{- $path := printf "dashboards/%s.json" $key }}
  {{ $key }}.json: |
{{ $root.Files.Get $path | indent 4 }}
  {{- end }}
{{- end -}}
```

Any way, changing the files don't have any effect on the diff.
the `helm upgrade --dry-run --debug`  when diffed showed the dasboard change.

After the update even if a do a `helm diff revision grafana 4 5` 
The diff between the manifests seems ok..
`helm get manifest grafana --revision 5`
`helm get manifest grafana --revision 4`

It shows as if the charts have been deleted.

I can provide more data if needed, for example maybe the output for each revision.

Just let me know what kind of data you need. The jsons are huge...

```
$ helm version
Client: &version.Version{SemVer:"v2.10.0", GitCommit:"9ad53aac42165a5fadc6c87be0dea6b115f93090", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.10.0", GitCommit:"9ad53aac42165a5fadc6c87be0dea6b115f93090", GitTreeState:"clean"}
$ helm plugin list
NAME    VERSION         DESCRIPTION
diff    2.10.0+1        Preview helm upgrade changes as a diff
```

**Comment by mumoshu** [comment]
@sfrique Thanks for the report!

I'm still trying to understand this, but basically your report seems to indicate that `helm-diff` should print correct diffs as long as it is actually loading the same data as that of commands like `helm get manifest grafana --revision 5`, right?

**Comment by sfrique** [comment]
I am sorry about the report, it was late and i just wanted to report that day, otherwise I wouldn't report.

I didn't check the code and look how helm diff actually diffs the file. But I assume, since the manifests are right, they should work.

This is a snippet of the last part of the command: `helm diff revision grafana 4 5`
```
default, grafana-clusterrolebinding, ClusterRoleBinding (rbac.authorization.k8s.io) has been removed:
- # Source: grafana/templates/clusterrolebinding.yaml
- kind: ClusterRoleBinding
- apiVersion: rbac.authorization.k8s.io/v1
- metadata:
-   name: grafana-clusterrolebinding
-   labels:
-     app: grafana
-     chart: grafana-1.11.4
-     release: grafana
-     heritage: Tiller
- subjects:
-   - kind: ServiceAccount
-     name: grafana
-     namespace: default
- roleRef:
-   kind: ClusterRole
-   name: grafana-clusterrole
-   apiGroup: rbac.authorization.k8s.io
+ 
default, grafana, Role (rbac.authorization.k8s.io) has been removed:
- # Source: grafana/templates/role.yaml
- apiVersion: rbac.authorization.k8s.io/v1beta1
- kind: Role
- metadata:
-   name: grafana
-   labels:
-     app: grafana
-     chart: grafana-1.11.4
-     heritage: Tiller
-     release: grafana
- rules:
- - apiGroups:      ['extensions']
-   resources:      ['podsecuritypolicies']
-   verbs:          ['use']
-   resourceNames:  [grafana]
+ 
```
And it's like this for everything else (as long as i checked)

But the diff between regular diff of manifest:
```
$ helm get manifest grafana --revision 5 > /tmp/grafana-rev5
$ helm get manifest grafana --revision 4 > /tmp/grafana-rev4
$ diff /tmp/grafana-rev4 /tmp/grafana-rev5
```
Show only  the new json that i've added.
