### ISSUE TITLE
Please release 2.10.0+2

### ISSUE THREAD

**Issue by henrikb123** [databus23/helm-diff#99]
Hi,

Could someone please make a proper release of 2.10.0+2 so that we can start using the --set-file functionality :)

**Comment by Starefossen** [comment]
Yes, need the `--set-file` functionality as well.

**Comment by XBeg9** [comment]
Any updates here?

**Comment by XBeg9** [comment]
I am getting errors: `unknown flag: --set-file` @mumoshu

**Comment by databus23** [comment]
I just released v2.11.0+1 which supports the `--set-file` flag.
